### ISSUE TITLE
share file by sending email

### ISSUE THREAD

**Issue by annrui** [sjarvela/kloudspeaker#1]
I am looking for another action "email" to send files by email as attachment. I took some time to find out, however I have trouble to get file direct path to attach.  Is there any way to get this?

**Comment by Bossanovation** [comment]
Hi there, I'm looking for exactely the same thing, I'm trying to figure out whithout success unfortunately! Is there anybody who would know what is the 'SendViaEmail' Plugin and how to use it? It would be very usefull... Thanks in advance

**Comment by annrui** [comment]
Maybe it can be done using plugin. but you need write all codes for this services.   or waiting for this will be added as one more services in backend by mollify.

**Comment by Bossanovation** [comment]
Thank you for your answer.
I'm developping this option at the moment...

**Comment by sjarvela** [comment]
There is a plugin stub in the package, called "SendViaEmail". It is draft that does not yet have client side at all, but service side shows approximately how it could work.

**Comment by Bossanovation** [comment]
Thanks for answering !
I'll study this plugin then...

**Comment by annrui** [comment]
What I found out is we need to finish client side by implementing draft "Send via email -plugin" in mollify.js including the dialog(might need to add new function for email forms in Dialogs and change template dialog.html), function to call service side.....

**Comment by sjarvela** [comment]
Version 2.7 had working draft version of plugin "SendViaEmail"
