### ISSUE TITLE
Error with a cyrillic symbols in names of the folders/files and some troubles with translations

### ISSUE THREAD

**Issue by Zegordo** [sjarvela/kloudspeaker#101]
Doesnt work filesystem (dont open) with russian names like Cyrillic. In Kloud written "Request failed". So no one can work with folders, which contains files with cyrillic symbols or with the same named folder.

php log:
[23-Jan-2016 20:03:37 Europe/Helsinki] KLOUDSPEAKER ERROR: 
{0:{file:C:\xampp\htdocs\kloudspeaker\backend\db\mysql\MySQLIDatabase.class.php, line:165, function:query, class:MySQLIDatabase, type:->, args:{0:INSERT INTO kloudspeaker_item_id (id, path) VALUES ('56a3c0793a7bd','1:/며鬨��﩮xlsx')}}, 
1:{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\ItemIdProvider.class.php, line:97, function:update, class:MySQLIDatabase, type:->, args:{0:INSERT INTO kloudspeaker_item_id (id, path) VALUES ('56a3c0793a7bd','1:/며鬨��﩮xlsx')}}, 
2:{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\ItemIdProvider.class.php, line:26, function:getOrCreateItemId, class:ItemIdProvider, type:->, args:{0:1:\며鬨��﩮xlsx}}, 
3{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\KloudspeakerFilesystem.class.php, line:88, function:getItemId, class:ItemIdProvider, type:->, args:{0:1:\며鬨��﩮xlsx}}, 
4:{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\LocalFilesystem.class.php, line:152, function:itemId, class:KloudspeakerFilesystem, type:->, args:{0:며鬨��﩮xlsx}}, 
5:{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\FilesystemItem.class.php, line:165, function:items, class:LocalFilesystem, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [56a3bd2b31f40] = 'доки' ()}}, 
6:{file:C:\xampp\htdocs\kloudspeaker\backend\include\filesystem\FilesystemController.class.php, line:598, function:items, class:Folder, type:->, args:{}}, 
7:{file:C:\xampp\htdocs\kloudspeaker\backend\include\services\FilesystemServices.class.php, line:309, function:items, class:FilesystemController, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [56a3bd2b31f40] = 'доки' ()}}, 
8:{file:C:\xampp\htdocs\kloudspeaker\backend\include\services\FilesystemServices.class.php, line:379, function:getFolderInfo, class:FilesystemServices, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [56a3bd2b31f40] = 'доки' (), 1:1, 2:{parent-metadata:{}, core-file-modified:{}}}}, 
9:{file:C:\xampp\htdocs\kloudspeaker\backend\include\services\FilesystemServices.class.php, line:67, function:processPostFolder, class:FilesystemServices, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [56a3bd2b31f40] = 'доки' ()}}, 
10:{file:C:\xampp\htdocs\kloudspeaker\backend\include\services\ServicesBase.class.php, line:69, function:processPost, class:FilesystemServices, type:->, args:{}}, 
11:{file:C:\xampp\htdocs\kloudspeaker\backend\include\KloudspeakerBackend.class.php, line:85, function:processRequest, class:ServicesBase, type:->, args:{}}, 
12:{file:C:\xampp\htdocs\kloudspeaker\backend\r.php, line:81, function:processRequest, class:KloudspeakerBackend, type:->, args:{0:Request}}}

며鬨��﩮xlsx - It is the cyrillic-named excel file, in the original looks "кирилица лол.xlsx"

**Comment by Zegordo** [comment]
in linux there was no cyrillc problems, but kloud can create a new folder only in a /backend  directory and doesnt see the server path  (like \serverIP\folder). Kloud just create a folder in a  /backend  directory  with \serverIP\folder name.

also, where is i can change localization of the share plugin, cause i have some troubles with translation: i did an operations, according to: https://github.com/sjarvela/kloudspeaker/wiki/Languages
but anyway, have text like !ru:configSystemNavTitle, !ru:shareDialogQuickShareTitle, !ru:shareViewConfirmDownloadTitle and so on.

**Comment by sjarvela** [comment]
If every part of the system including server OS filesystem, database, web server etc, supports UTF-8, there should be no problems with cyrillic letters, I have tested with many languages like chinese, japanese, russian etc.

If your folders created are ending up at "backend", it is not suggested configuration. Folders should be located elsewhere, outside the app folder, so that updates etc are easier. See https://github.com/sjarvela/kloudspeaker/wiki/Security

For the share plugin localizations, plugins have their own localization folder (and remember to change the language id inside the file also)

**Comment by sjarvela** [comment]
Also, see this issue related to charsets https://github.com/sjarvela/kloudspeaker/issues/95
