### ISSUE TITLE
Group Properties not showing.

### ISSUE THREAD

**Issue by lordloh** [sjarvela/kloudspeaker#104]
Clicking on group name in admin > groups > group name does not bring up the group properties. It used to in the latest stable release of Mollify.
![capture](https://cloud.githubusercontent.com/assets/2434923/12604665/6e4e2190-c472-11e5-9bb4-be72f71d8d10.PNG)

**Comment by sjarvela** [comment]
Fixed, will be in next release

**Comment by lordloh** [comment]
Issue still exists in 2.7.12 (rev. 40)

**Comment by lordloh** [comment]
Confirm that the issue is fixed :-) Had to refresh twice to see it work.
