### ISSUE TITLE
trim user input on CreateFolder() call - trailing spaces break the system

### ISSUE THREAD

**Issue by b-and-p** [sjarvela/kloudspeaker#110]
This is an old issue, from Mollify yet.
When user provides a folder name with trailing spaces, it effectively breaks the system, the offending directory is not accessible via kloudpseaker:
`{"code":999,"error":"Unexpected server error","details":"PHP error #2, filemtime(): stat failed for path\to\folder  ....`

renaming or deleting directory with trailing space is also problematic on Windows - Windows Explorer fails, need to use command prompt and short filename (`dir /X; rmdir foobar~1`) to delete or rename the offending directory.

Proposed solution:
in .\backend\include\filesystem\LocalFilesystem.class.php

replace:
`public function createFolder($folder, $name) {`

with
`public function createFolder($folder, $name) {
            $name = trim($name);`

**Comment by sjarvela** [comment]
Makes sense. I was only thinking whether trimming should be done differently, or on more generic level. For example can there be files with leading/trailing spaces? Or should this be matter of data validation, ie reject create request if there are such values. There even could be filesystems where this isn't a problem, should it then be possible?

**Comment by sjarvela** [comment]
Well, I added now trimming by default, let's make it optional etc if there is need

**Comment by b-and-p** [comment]
Alright, this is good.
Below my arguments before I saw your second post.

---

>  I was only thinking whether trimming should be done differently, or on more generic level. 

By all means, I am sure you have a better place / way to do this, as the author of the system

> For example can there be files with leading/trailing spaces?
> ... There even could be filesystems where this isn't a problem, should it then be possible?

I don't think there will be ever such need, Windows automatically trims filenames, unless you create them via some script. Trailing spaces in filenames are probably not even possible, since it would break the extension. Leading and trailing spaces in folder or file names are invisible on screen and in print, and will cause users confusion if anything. Even if some filesystems would allow it, it doesn't mean it **should** be done, in most (or all) cases it would be due to user's negligence.

> Or should this be matter of data validation, ie reject create request if there are such values.

I think it would be best to handle this on input, yes. But instead of rejecting request, I would silently conform the string to system requirements (i.e. trim it, remove illegal chars etc.)
