### ISSUE TITLE
Cannot add user to groups form the group menu.

### ISSUE THREAD

**Issue by lordloh** [sjarvela/kloudspeaker#111]
![capture](https://cloud.githubusercontent.com/assets/2434923/12992145/55f0c860-d0d8-11e5-867c-7f703cebfd3f.PNG)

I am using 2.7.12 (rev. 40)

Clicking on the "+" does not show me any users (there are freshly created users on the system).

I may however go to the user menu and add group memberships to individual users.

**Comment by sjarvela** [comment]
Fixed, will be in next release

**Comment by sjarvela** [comment]
In 2.7.13
