### ISSUE TITLE
After installation... how to log in as admin?

### ISSUE THREAD

**Issue by karlol8** [sjarvela/kloudspeaker#112]
Hey everybody, I have a stupid question: what next after install kloudspeaker? I read I have to log in as admin, but I can't find out how. Threre is no page with login-box, there is no folder called "admin" or simillar. I thought I could be able to use the backend to configure kloudspeaker... 
Oh, and when I want to open /kloudspeaker/index.html I see this alert:

> !null:errorDialogTitle
> 
> !null:errorDialogUnknownError

When installation is complete i see this: 

> Kloudspeaker is successfully installed
> 
> You can now log into Kloudspeaker using the admin account created.
> 
> For additional configuration options or instructions, see Installation instructions. 

so everything should be fine, but isn't. Somebody help, please ? :)

**Comment by sjarvela** [comment]
Well, there seems to be some configuration etc error that prevents the app from getting so far to display login page.

Since it does not even being able to determine & load language, I suspect the error is in index.html. Take a look at the browser log, if you made changes to that file and perhaps made syntax error etc

**Comment by CbPat** [comment]
Hi, i have the same issue with installation
in chrome browser log:

> http://mydomain.com/backend/r.php/session/info/ Failed to load resource: the server responded with a status of 404 (Not Found)

kloudspeaker run under nginx 1.9.8.1 Kitty

**Comment by sjarvela** [comment]
You could try with this option: https://github.com/sjarvela/kloudspeaker/wiki/Client-configuration-options#service-param-service-param

**Comment by Jellyebanz** [comment]
Hello, I have been having the same issue as the OP, I'm confused as to why because I haven't edited index.html at all, just followed the installer. Is this a known error?

**Comment by Tjr25** [comment]
Hi, I have the same problem here. I have not edited the index.html file at all. Simply run through the installer and then get the error alert below when trying to open the root document to log in.  I am using IIS 7.0

Also I did try with and without the service-param option as suggested and this made no difference

And having run it through a debugger it's failing with 500 (Internal Server Error) trying to get  the page http://localhost/backend/r.php/session/info/

**Comment by thanhngch** [comment]
I have same issue. I configure it success and I can't login. I run it in Nginx server. How config Nginx serrver to run it?

**Comment by Tjr25** [comment]
Anyone managed to fix this? I wonder if it's a PHP setting at all what need changing. I'm just using the default PHP settings.

**Comment by Jellyebanz** [comment]
Not as yet, I'm getting desperate now

On Monday, 9 May 2016, Tjr25 notifications@github.com wrote:

> Anyone managed to fix this? I wonder if it's a PHP setting at all what
> need changing. I'm just using the default PHP settings.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/sjarvela/kloudspeaker/issues/112#issuecomment-217874463

## 

Sent from Gmail for iPad

**Comment by sjarvela** [comment]
Well, here's two different things.

1) if you get 404, it means server says there is nothing here.

In this case, check first that if the path is really correct. If it s, then try with browser "http://mydomain.com/backend/r.php", it should return some JSON data (but not 404). It even this fails, there is something wrong with installation.

But if this works, then "service-param" should help, as there is technical difference between ".../r.php/session/info" and ".../r.php?sp=/session/info"

2) if you get 500 internal server error, it means PHP handles it but there was some error

In this case, you need to check the PHP error log.

**Comment by thanhngch** [comment]
With me: http://mydomain.com/backend/r.php show {"code":0,"error":"Unknown error: Empty request","details":"","data":null,"trace": [...] backend\/r.php, line:81, function:processRequest, class:KloudspeakerBackend, type:->, args:{0:Request}}}","RESPONSE error {0:0, 1:Unknown error: Empty request, 2:403}
And I inspect it in tab network, I see "http://mydomain/kloudspeaker/backend/r.php/session/info/" has status 404.
I use PHP 7 and Nginx server in my server.

**Comment by sjarvela** [comment]
@thanhngch that response is just fine, which means you either need to use option "service-param", or configure nginx somehow, not sure what is the problem there

**Comment by Jellyebanz** [comment]
Hi,

I went to backend/r.php and got the following:

{"code":999,"error":"Unexpected server error","details":"PHP error
#8192, Methods with the same name as their class will not be
constructors in a future version of PHP; PasswordHash has a deprecated
constructor (\/customers\/1\/2\/a\/theituk.org\/httpd.www\/docman\/backend\/vendor\/phpass\/PasswordHash.php:27)","data":null}

Thanks

Clare

**Comment by sjarvela** [comment]
I've modified the vendor library now to be PHP7 compliant.

**Comment by sjarvela** [comment]
released in 2.7.15

**Comment by and-jan** [comment]
Just FYI, if anyone else still receives this error message and is running kloudspeaker on nginx in the root directory on the webserver, just add this line to the vhost config:
`location / {
                try_files $uri $uri/ /backend/r.php?$args;
        }`
