### ISSUE TITLE
Assign new or change existing user password appears to be not possible

### ISSUE THREAD

**Issue by b-and-p** [sjarvela/kloudspeaker#113]
I've been poking around the system for a couple of hours now. Not sure if I am missing something obvious, but I cannot seem to be able to achieve any of the following:
- Change **Admin1** user password (Logged in as **Admin1**)
- Change **Admin2** user password (Logged in as **Admin1**)
- Change user (created w/o password as _ldap_) login type from _ldap_ to _pw_ and assign a default password.
- Change password logged in as **User1** (no password field on account page), user permission for "Change password" is set to _Yes_, user login type is _pw_

Start to feel real stupid now, but cannot find password add/change option anywhere in the interface.

I did set `"enable_change_password" => TRUE,` 

Any help is appreciated.

**Comment by sjarvela** [comment]
The change password option is in the user menu, in top right corner where you can log out.

Also, admins can change passwords in user admin view, in the list there is a key icon for each user.

**Comment by b-and-p** [comment]
Sorry, I don't see it. I am trying to change password of the main admin user (the one the installation was done with)

![ks_userpass_issue_0001](https://cloud.githubusercontent.com/assets/8944029/13210082/666b0e08-d966-11e5-9ffc-83ca2b0bbf89.jpg)

![screen shot 2016-02-22 at 01 10 pm](https://cloud.githubusercontent.com/assets/8944029/13210093/806f549e-d966-11e5-8395-d7d6134ecc5d.PNG)

![screen shot 2016-02-22 at 01 11 pm](https://cloud.githubusercontent.com/assets/8944029/13210094/87c3b398-d966-11e5-911b-b3fead965407.PNG)

**Comment by b-and-p** [comment]
Found the cause of list icon not showing, for some reason `type` field in `user_auth` table is in upper case (PW | LDAP), I change the following line in `js/kloudspeaker/config/users.js` (line 130):

```
return (auth == 'pw');
```

to 

```
return (auth.toLowerCase() == 'pw');
```

Now key icon is showing, still don't have the "change password" option in user menu (top right)

**Comment by b-and-p** [comment]
Alright, found the second one as well - same reason (upper case record in DB - "PW")

Edited `\js\kloudspeaker\ui\views\main.js` line (323), changed:

```
if (features.hasFeature('change_password') && s.user.auth == 'pw' && permissions.hasPermission("change_password")) {
```

to 

```
if (features.hasFeature('change_password') && s.user.auth.toLowerCase() == 'pw' && permissions.hasPermission("change_password")) {
```

Now it all works as you described.

Not sure if this is a bug, or my data is at fault. My database is few years old, I brought it in from Mollify. didn't have chance to test with clean install of kloudspeaker.

**Comment by sjarvela** [comment]
Interesting, probably is migration issue, I'll check if there is something that should be done differently with the auth value, perhaps convert it to lowercase in server side just in case

**Comment by sjarvela** [comment]
Lowercase convertion was added in earlier release
