### ISSUE TITLE
Multiple users with same email not allowed

### ISSUE THREAD

**Issue by ghmerrill** [sjarvela/kloudspeaker#115]
Kloudspeaker does not allow the creation of two users with the same email.  There really isn't any reason why this should NOT be allowed, and there is utility to it in certain circumstances (even, for example, just in testing).

Kloudspeaker DOES allow the creation of multiple users with NO email address.  So there is certainly some inconsistency here.

**Comment by sjarvela** [comment]
Why should there be many users with same email? For example, resetting passwords is impossible if emails are not unique. And since it is possible to allow logging in with email, this is also a reason for not letting duplicate emails.

No email is different case, users without email just cannot
a) login with email
b) cannot reset password
c) cannot receive notifications

**Comment by ghmerrill** [comment]
Your arguments here are quite incorrect.

From a USER perspective the question is not "Why should there be multiple users with the same email?", but "Why should there NOT be multiple users with the same email?"  A user says "This is what I want", and you respond with "You shouldn't want that."  Not a good approach.

Resetting passwords is impossible in the case of non-unique emails ONLY if you identify a user strictly with an email address -- only if you use the email address as the "key" or identifying characteristic of a user.  So why do this (and in fact, you DON'T do this)?  In order to log in, the user may provide his user Id and password -- and NOT his email.  You DON'T -- so far as I can see -- use the email address as the definitive key.  See my comment below concerning your claim about your list item b)

So:  Why allow logging in with an email address?  This is completely unnecessary and adds no additional utility.  If someone WANTS to use his email address AS his user Id, then THAT is simple enough and can be done now.  Try it.  It works just fine.  So if you want to use your email as your user Id, then just create the account with it as BOTH your user Id AND as your email.  This works.  And if you wanted to, you could easily handle the case of using email addresses to log in even in the case of non-unique ones.  In cases where there is only one instance of the email address in your user list, allow the login.  In the case where multiple users share an email address, return an error and informative message to this effect, and tell the user that he must log in with his user ID.  No problem.

As an example of WHY someone might want two user accounts with a single email:  I at times run into the situation where a married couple share a single email account but want two separate user IDs.  This isn't unusual, and there is NO reason not to support it.  There are other similar scenarios where members of a group (or users from a company) might want distinct user Ids but a single "Kloudspeaker email" account.  There is absolutely nothing wrong with this, and no reason not to support it, and no reason why any messages from Kloudspeaker cannot indicate to the recipient the Kloudspeaker Id to which they are being sent -- since you always know this when you send the email.

You say "No email is a different case, users without email just ... b) cannot reset password."  Yes they can.  Haven't you tested this stuff?  I just created a user with no email and then logged in on that account and changed the password.  No problem.

Your arguments against allowing multiple IDs with the same email address are arguments of a coder bound to his current implementation.  They are not arguments based on user needs and usability.  They are the coder's response of "I can't do that."  Yes, you can.

**Comment by nnmalex** [comment]
Dude, you are being unreasonable.

Resetting password involves email with a link so in your case all users with one email will get a link for one user. That's a security flaw.

Can you name one well known php script that would allow what you are asking for as exemple?

I don't think many users would like to see such functional.

**Comment by ghmerrill** [comment]
“Resetting password involves email with a link so in your case all users with one email will get a link for one user.”

Can you explain what this means?  What does “involves email with a link” mean?  And what does “get a link for one user” mean?

In addition, while Kloudspeaker does not allow the CREATION (ab initio) to two accounts with the same email address, it DOES allow the administrator to CHANGE an email address to the same one as on an existing account.  Try it.  Have you tested this?

What exactly is the “security flaw” you are referring to?  I’m not seeing a security flaw here.

“Can you name one well known php script that would allow what you are asking for as exemple?”

This is a question about current implementation.  It’s irrelevant to the discussion.  It’s just a rephrasing of “This is how people usually do things,” and doesn’t address a specific usability request based on a valid scenario.

“I don't think many users would like to see such functional.”

You don’t THINK?  Well, that’s not a very strong argument.  I think otherwise.  In fact, you have NO evidence concerning how many users would like to see this feature.   Developers often “don’t think” users will want anything other than what the developers are willing or able to give them.  I’ve provided clearly valid scenarios that I’ve encountered in practice.  And I still don’t see any reason NOT to support this feature.  If you feel strongly about it, you should at least add an issue to prohibit the administrator from allowing multiple users to share an email address.  Have you tested any of these things?  Do you run regression tests?

---

Gary H. Merrill

Chatham Design Consultants

+1 919.271.7259

**Comment by sjarvela** [comment]
Let's not get carried away with this. Perhaps you don't understand what I'm referring as "resetting password", it's not same as "logging in and changing password". It's the case you have forgotten password, and you need to reset it (from the login screen), ie you request a reset password link into your email.

It's true administrator can change email to be same as some other, I'll have to fix that.

I don't think it's that invalid point to ask is there any other _well known_ system that allows multiple accounts with same email?

Right now if you reset password, you only need to give email address, nothing else. That simply does not work if you cannot know which user it is targeted at. Sure, there could be some other key as well, but having unique email this is the simplest way, and simplicity is usually good.

Your scenario of married couple using same email address is a) maybe the only scenario I can think of (still very curious why would even married couple use same email? but that's not relevant, though) b) very marginal.

I don't say "it cannot be like this" or "I don't want to do it like this", but for every case I need to evaluate the value, how many users actually would need this? This does not seem very common need, unfortunately
