### ISSUE TITLE
is possible to create corn jobs as a plugin? 

### ISSUE THREAD

**Issue by sureshamk** [sjarvela/kloudspeaker#116]
Hi I Appreciate a work behind this project, such a nice project . I found a one missing feature or i don't know which is exist here , but i would like do some corn jobs in **kloudspeaker** , for example a would like to get a status mail from this system at particular time of every day. Is here any way to implement with in the plugin system ?.

**Comment by sjarvela** [comment]
You mean cron jobs?

Well, cron is linux tool, nothing to do with PHP apps. It goes the other way, you can assign cron jobs that trigger scheduled actions via making web requests.

Adding actions that can be triggered from cron is not difficult, there is already Kloudspeaker command interface, I'm sure those could be used.

I know there are PHP scripts that can use SSH library to modify crontab, but I'm not sure if that's good path.
