### ISSUE TITLE
Can't use file "View" function anymore since 2.7.13

### ISSUE THREAD

**Issue by dejavuzxy** [sjarvela/kloudspeaker#118]
Since the latest 2.7.13 update I can't seem to be able to "View" image file (like png or jpg) or some music file (like mp3) or video file (like mp4) anymore. It worked fine on the previous update, but does not work on the new one. PHP Error Log also shows nothing at all and no error messages pop up. When pressed the "View" button, nothing happens and the dialog box disappears.

Can this be a bug caused by the File Viewer/Editor update?

**Comment by luchris** [comment]
Yes. I am also having issue. PDF with Direct also not working

**Comment by sjarvela** [comment]
Can't see any problems myself. Did you update the backend folder as well? Are there any errors in browser console? Does it happen with every browser?

**Comment by dejavuzxy** [comment]
Yes, this happens with every browser and i can't see any errors in browser console. Also yes, the backend was updated as well. I even double-checked that bit.
It works fine with the last update, but does not work with the new update.

**Comment by sjarvela** [comment]
Would it be possible for me to have access to the site? If it is, post me any details into my email

**Comment by dejavuzxy** [comment]
Sorry for the late response, was working. It seems randomly the bug has disappeared, for me at least. Perhaps it was some sort of web server cache problem where something didn't get cleaned up properly and old file versions were served. Anyway for me, the problem is gone, don't know about the other guy.

**Comment by sjarvela** [comment]
Closing until further info
