### ISSUE TITLE
Issue installing on webserver

### ISSUE THREAD

**Issue by dsburny** [sjarvela/kloudspeaker#119]
I have installed Kloudspeaker on a web host, all ran successfully. When I load the index page, it displays a white screen.
I have attached the javascript error which is appearing in the developer console.
Any ideas what could be wrong?
![capture](https://cloud.githubusercontent.com/assets/17440458/13269369/53117224-da7f-11e5-986c-bc5ae11deddb.PNG)

**Comment by sjarvela** [comment]
Unfortunately, not based on this. The error seems like there is malformed JSON somewhere, but hard to say where.

Please see PHP error log first to see if there was some error, which would produce malformed result.

**Comment by dsburny** [comment]
Yeah, I realised this is not much information. I have tried looking at the error log but it doesnt give much information about any error. I have been trying to debug the issue, and the error was occurring on line 17693 of kloudspeaker.js, where it is calling json.Parse(e.responseText). From stepping through the code leading to this, it appears to be an ajax call to r.php/session/info. I have looked at the responseText, and it does appear to be being truncated for some reason? I am not aware of any settings that might cause this?

The data that is returned in e.responseText:
`"{"result":{"authenticated":false,"features":{"limited_http_methods":false,"change_password":true,"descriptions":true,"user_groups":true,"mail_notification":false,"retrieve_url":false,"folder_protection":false,"thumbnails":true,"guest_mode":false,"file_view":true,"file_preview":true,"file_edit":true},"resources":{"custom_url":null},"plugins":{"FileViewerEditor":{"custom":false,"admin":false,"client_module_path":"http:\/\/abc.co.uk\/kloudspeaker\/backend\/plugin\/FileViewerEditor\/client\/","client_module_id":"kloudspeaker\/fileviewereditor"},"ItemDetails":{"custom":false,"admin":false,"client_module_path":"http:\/\/abc.co.uk\/kloudspeaker\/backend\/plugin\/ItemDetails\/client\/","client_module_id":"kloudspeaker\/itemdetails"}},"version":"2.7.13","revision":4"`

Does this shed any more light on what the issue could be?

Thanks

**Comment by sjarvela** [comment]
if that really is all the response, then sure it fails, that's not valid json

Haven't seen before this kind of response truncating, and any reason can be only found in PHP side, not client.

Do you have some kind of compression or accelerator enabled in PHP? If you do have, you could try disabling them and trying again

**Comment by sjarvela** [comment]
Closing until further info
