### ISSUE TITLE
Problem with CKEditor plugin version 1.0 zip size 870947 bytes

### ISSUE THREAD

**Issue by luke7263** [sjarvela/kloudspeaker#12]
I notice 2 problems in the logs:
- File not exists: backend/plugin/FileViewerEditor/editors/CKEditor/resources/kloudspeaker.js
    => easy to solve, just rename the existing mollify.js in kloudspeaker.js
- File not exists: backend/plugin/FileViewerEditor/editors/CKEditor/resources/config.js
    => here there is only an existing ckeditor.js file, seems not to be any config stuff inside, so is it really missing ? 

However I've tried to edit an HTML file and it seems working ..;)

**Comment by sjarvela** [comment]
This has been forgotten to update. Although editor has been fixed long time ago, now 1.1 has been released with 2.7.8.
