### ISSUE TITLE
New folder, upload, navigation buttons not displaying

### ISSUE THREAD

**Issue by rserentill** [sjarvela/kloudspeaker#121]
Just installed version 2.7.13, and the menu that allows you to create folders, upload files and navigate through the directories, is not being displayed. So I can't create new folders or add new files.

I tried to install from 0 twice. Tested it with Chrome and Firefox.

An screenshot is attached.

![screenshot](https://cloud.githubusercontent.com/assets/10400822/13505614/253e8e5c-e17a-11e5-93d3-727ccb052d15.PNG)

**Comment by sjarvela** [comment]
Do you have any folders defined in configuration/folders?

**Comment by sjarvela** [comment]
Based on screenshots (not showing any folders), I assume this is configuration issue, closing until further info
