### ISSUE TITLE
Unit Testing is missing

### ISSUE THREAD

**Issue by sureshamk** [sjarvela/kloudspeaker#122]
I could not found any unit testing involved from this nice project . I expecting some unit testing involvement  for developer to contribute

**Comment by sjarvela** [comment]
I'm painfully aware of unit tests missing, and the main reason (=excuse) is lack of time. The project started from a whole different goal, and I've been slowly rewriting client side into more modular way, which would make it easier to unit test. Backend is another story, I've been looking for platform products that would replace custom made REST service, also postponing unit testing for that.

I think Aurelia branch will be the future master, and for that I will start building also tests.
