### ISSUE TITLE
Browser back/forward buttons aren't working. 

### ISSUE THREAD

**Issue by jonas-fortytwo** [sjarvela/kloudspeaker#125]
The browser back and forward buttons aren't working. 
Anybody got any idea how to fix that?

Thanks

**Comment by sjarvela** [comment]
It's true, back/forward buttons are not handled correctly. There is feature that reflects the view in browser URL (https://github.com/sjarvela/kloudspeaker/wiki/Client-configuration-options#reflect-view-in-url-view-url), but I suppose handling back/forward should be possible as well, I'll investigate.

**Comment by sjarvela** [comment]
Fixed in https://github.com/sjarvela/kloudspeaker/commit/dca5bc2d405d128354d66af6706fc9d9858846ff
