### ISSUE TITLE
Issues creating a new folder 

### ISSUE THREAD

**Issue by carlosamaya** [sjarvela/kloudspeaker#126]
Hi fellows, i have the problem that mollify (Im still using mollify) cant create new folders, but the Folders are in the same web-server, the user that owns the folder is www-data i think its the same user that PHP uses, also i changed the folder access to 777 and even so doesnt grant me acces to mkdir...please help:

MySQLi DB: mollify@localhost:mollify(mollify_)
EVENT HANDLER: registering '*': EventLogger
DB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '15727379954bed' and last_access >= 20160502045854
DB QUERY: select name, value from mollify_session_data where session_id = '15727379954bed'
DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='79' AND (expiration is null or expiration > 20160502065854)
DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '79') ORDER BY id ASC
DB QUERY: UPDATE mollify_session set last_access=20160502065854 where id='15727379954bed'
Filesystem registered: local
EVENT HANDLER: registering 'filesystem/': FilesystemController
VERSION: 2.6.7 SERVER: {PHPRC:/opt/php/bin/php-5.3.3/bin/etc/php.ini, PWD:/var/www/cgi-bin, FCGI_ROLE:RESPONDER, REDIRECT_HANDLER:php-cgi, REDIRECT_STATUS:200, CONTENT_LENGTH:62, HTTP_ORIGIN:http://0.0.0.0, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_MOLLIFY_SESSION_ID:15727379954bed, CONTENT_TYPE:application/json, HTTP_REFERER:http://0.0.0.0/visdoc/?v=admin/folders, HTTP_COOKIE:PHPSESSID=iegh96m8rqvs286k4mvu9uggr0; mollify_app_session=15727379954bed, HTTP_X_BLUECOAT_VIA:f353c8eb22c0e2cd, REQUEST_SCHEME:http, CONTEXT_PREFIX:/php5-cgi/, CONTEXT_DOCUMENT_ROOT:/var/www/cgi-bin/, SCRIPT_FILENAME:/var/www/php-5.3.3/visdoc/backend/r.php, REDIRECT_URL:/visdoc/backend/r.php/configuration/folders, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:, REQUEST_URI:/visdoc/backend/r.php/configuration/folders, SCRIPT_NAME:/visdoc/backend/r.php, PATH_INFO:/configuration/folders, PATH_TRANSLATED:/var/www/configuration/folders, ORIG_PATH_INFO:/visdoc/backend/r.php/configuration/folders, ORIG_SCRIPT_NAME:/php5-cgi/php-5.3.3.fcgi, ORIG_SCRIPT_FILENAME:/var/www/cgi-bin/php-5.3.3.fcgi, ORIG_PATH_TRANSLATED:/var/www/php-5.3.3/visdoc/backend/r.php/configuration/folders, PHP_SELF:/visdoc/backend/r.php/configuration/folders, REQUEST_TIME:1462188534}
SETTINGS: {db:{type:mysql, user:mollify, password:, host:localhost, port:3306, database:mollify, table_prefix:mollify_, charset:utf8_general_ci, engine:MyISAM}, plugins:{FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}}, previewers:{Image:{0:gif, 1:png, 2:jpg, 3:jpeg}}}, ItemDetails:{}, EventLogging:{}}, timezone:America/Caracas, convert_filenames:1, authentication_methods:{0:pw, 1:ldap}, ldap_server:ldap://XXXX.com, debug:1, debug_log:/var/www/php-5.3.3/visdoc/logs/visdoc_XXXX.log}
FEATURES: {limited_http_methods:, change_password:1, descriptions:1, user_groups:1, mail_notification:, retrieve_url:, folder_protection:, thumbnails:, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}
FILESYSTEM: allowed_file_upload_types={}
SESSION: is_active=1, user={id:79, name:XXXl, user_type:a, lang:, email:XXXX@XXXXXXX.com, expiration:20180131142544, auth:}, data={auth:}
AUTH: is_authenticated=1
REQUEST: method=post, path={0:configuration, 1:folders}, ip=0.0.0.0, params={}, data={name:HomeFolder, path:/MiDoc/HomeFolder, create:1}
SERVICE (ConfigurationServices)
Added folder does not exist, creating: /MiDoc/HomeFolder
PHP error #2, mkdir(): Permission denied (/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php:43) {0:{function:globalErrorHandler, args:{0:2, 1:mkdir(): Permission denied, 2:/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php, 3:43, 4:{rootPath:/MiDoc/HomeFolder/}}}, 1:{file:/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php, line:43, function:mkdir, args:{0:/MiDoc/HomeFolder/, 1:493}}, 2:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ConfigurationServices.class.php, line:662, function:create, class:LocalFilesystem, object:LOCAL () HomeFolder(/MiDoc/HomeFolder/), type:->, args:{}}, 3:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ConfigurationServices.class.php, line:62, function:processPostFolders, class:ConfigurationServices, object:ConfigurationServices, type:->, args:{}}, 4:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ServicesBase.class.php, line:59, function:processPost, class:ConfigurationServices, object:ConfigurationServices, type:->, args:{}}, 5:{file:/var/www/php-5.3.3/visdoc/backend/include/MollifyBackend.class.php, line:85, function:processRequest, class:ServicesBase, object:ConfigurationServices, type:->, args:{}}, 6:{file:/var/www/php-5.3.3/visdoc/backend/r.php, line:81, function:processRequest, class:MollifyBackend, object:MollifyBackend, type:->, args:{0:Request}}}
RESPONSE error {0:999, 1:Unexpected server error, 2:500} PHP error #2, mkdir(): Permission denied (/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php:43)

**Comment by sjarvela** [comment]
It seems you trying to create "/MiDoc/HomeFolder", does the root "MiDoc" exist?

If it does, then you should recheck that it really is "www-data" that apache/PHP is running on

**Comment by carlosamaya** [comment]
the true path its /var/www/php-.5.3.3/mollify/backend/MiDoc....and yes, www-data owns MiDoc and subfolders

**Comment by sjarvela** [comment]
In this case, you cannot use path "/MiDoc/..." because that simply don't exist. In linux filesystem, if path starts with "/", it means "MiDoc" is under filesystem root.

In your case you would have to
1) use relative path, ie without "/" in the beginning, instead directly "MiDoc" or "../MiDoc" etc, whatever is correct. But this is not good solution if you intend to use WebDAV, it has different root and relative would point to wrong place
2) use absolute path, ie give the full path "/var/www/php-.5.3.3/mollify/backend/MiDoc/HomeFolder"
3) use published folder root (https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#published-folders-root-published_folders_root) to set root to "/var/www/php-.5.3.3/mollify/backend/MiDoc", and then you can use simply "HomeFolder" when adding folder in Kloudspeaker

But you should note that having published folders under backend folder is not adviced, it is easier to make updates if they are outside installation folder.
