### ISSUE TITLE
Problem with TextFile viewers 1.1 zip size 69046 (edit the post to watch the diff result, dirty display on list mode)

### ISSUE THREAD

**Issue by luke7263** [sjarvela/kloudspeaker#13]
When just view a txt file, the viewer popup stays empty an I have this error:

PHP Fatal error:  Call to undefined method TextFileViewer::getItemContent() in backend/plugin/FileViewerEditor/viewers/TextFile/TextFile.viewer.php on line 45

So I've compared with the previous one and here is the diff (the first is working, not the second):

diff -r TextFileOK/TextFile.viewer.php TextFile/TextFile.viewer.php
44,45c44,45
<                       // read file
## <                       $stream = $item->read();

> ```
>                   // read file
>                   $stream = $this->getItemContent($item);
> ```
> 
> 52c52
> ## <                       return "<html><head><title>".$item->name()."</title>".$head."</head><body>".$html."</body></html>";
> 
> ```
>                   return "<html><head><title>".(is_array($item) ? $item["name"] : $item->name())."</title>".$head."</head><body>".$html."</body></html>";
> ```
> 
> 56c56
> ## <                       $ext = $item->extension();
> 
> ```
>                   $ext = (is_array($item) ? $item["extension"] : $item->extension());
> ```

**Comment by sjarvela** [comment]
Function getItemContent was added to the ViewerBase class in 2.6.8. So updating textfile viewer to older version does not work.

Was it due to this? if it was, this issue should be closed
