### ISSUE TITLE
Error with copy multiply files

### ISSUE THREAD

**Issue by VadBar13** [sjarvela/kloudspeaker#130]
Hi!

I had an error, when I try to copy multiply files:
`PHP error #8, Undefined variable: replace (/srv/polly/html/kloudspeaker/backend/include/filesystem/FilesystemController.class.php:830`

I look into FilesystemController.class.php and noticed, that in "moveItems" function:
`FilesystemController.class.php:985: $this->env->events()->onEvent(MultiFileEvent::move($items, $to, $targets, $overwrite));`
but in "copyItems" function:
`FilesystemController.class.php:830: $this->env->events()->onEvent(MultiFileEvent::copy($items, $folder, $targets, $replace));`

And if I change "$replace" to "$overwrite" in FilesystemController.class.php:830, copy event works correctly.

Plz, fix it.

**Comment by sjarvela** [comment]
Fixed
