### ISSUE TITLE
Renaming folder with different case

### ISSUE THREAD

**Issue by karlneco** [sjarvela/kloudspeaker#135]
Hi

We got a user who created a folder with the wrong case and then tried to correct the letter case, that resulted in a error, the rename went through - but accessing the folder also produces an error

steps were as follows:
Create a folder named "NEw Folder"
Right click it and rename it to " New Folder"
got the following Error message 

`MySQLi DB: kloudspeaker@localhost:kloudspeaker()
EVENT HANDLER: registering 'filesystem/': ShareHandler
DB QUERY: select id, user_id, ip, time, last_access from session where id = '1573cab07cef28' and last_access >= 20160518190939
DB QUERY: select name, value from session_data where session_id = '1573cab07cef28'
DB QUERY: SELECT id, name, lower(user_type) as user_type, lower(lang) as lang, email, expiration, lower(ua.type) as auth FROM user left outer join user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20160518210939)
DB QUERY: select id, name, description from user where id in (SELECT user_group.group_id FROM user as user, user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASC
DB QUERY: UPDATE session set last_access=20160518210939 where id='1573cab07cef28'
Filesystem registered: local
EVENT HANDLER: registering 'filesystem/': FilesystemController
VERSION: 2.7.16 SERVER: {CONTENT_LENGTH:21, HTTP_ORIGIN:http://_example.com:9090_, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_KLOUDSPEAKER_SESSION_ID:1573cab07cef28, CONTENT_TYPE:application/json, HTTP_REFERER:http://_example.com:9090_/?v=files/573cafd76db99, HTTP_COOKIE:_ga=GA1.2.1905340459.1441130469; kloudspeaker_app_login=1%3A5d9c4bc7eec60862be282887ce951907; kloudspeaker_app_session=1573cab07cef28, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:/var/www, SCRIPT_FILENAME:/var/www/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:PUT, QUERY_STRING:, REQUEST_URI:/backend/r.php/filesystem/573cafdc69dfd/name/, SCRIPT_NAME:/backend/r.php, PATH_INFO:/filesystem/573cafdc69dfd/name/, PATH_TRANSLATED:/var/www/filesystem/573cafdc69dfd/name/, PHP_SELF:/backend/r.php/filesystem/573cafdc69dfd/name/, REQUEST_TIME_FLOAT:1463594979.972, REQUEST_TIME:1463594979}
SETTINGS: {db:{type:mysql, database:kloudspeaker, user:kloudspeaker, password:, charset:utf8}, plugins:{FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}}, ItemDetails:{}, Share:{}, Archiver:{compressor:ziparchive, enable_download:1, enable_compress:1, enable_extract:1}}, timezone:America/Edmonton, new_folder_permission_mask:493, debug:1}
FEATURES: {limited_http_methods:, change_password:1, descriptions:1, user_groups:1, mail_notification:, retrieve_url:, folder_protection:, thumbnails:, guest_mode:, file_view:1, file_preview:1, file_edit:1}
FILESYSTEM: allowed_file_upload_types={}
SESSION: is_active=1, user={id:1, name:akadmin, user_type:a, lang:, email:, expiration:, auth:}, data={auth:}
AUTH: is_authenticated=1
REQUEST: method=put, path={0:filesystem, 1:573cafdc69dfd, 2:name}, ip=192.168.1.112, params={}, data={name:New Folder}
SERVICE (FilesystemServices)
DB QUERY: select path from item_id where id='573cafdc69dfd'
DB QUERY: SELECT id, type, name, path FROM folder where id='35'
DB QUERY: select id from item_id where path='35:/'
DB QUERY: select id from item_id where path='35:/NEw Folder/'
rename from [NEw Folder/] to [New Folder]
EVENT HANDLER: onEvent: filesystem/rename
DB QUERY: UPDATE item_id SET path=CONCAT('35:/New Folder', SUBSTR(path, 15), level = -1 WHERE path like '35:/NEw Folder/%'
ServiceException: INVALID_CONFIGURATION=Error executing query (UPDATE item_id SET path=CONCAT('35:/New Folder', SUBSTR(path, 15), level = -1 WHERE path like '35:/NEw Folder/%'): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE path like '35:/NEw Folder/%'' at line 1
{0:{file:/var/www/backend/db/mysql/MySQLIDatabase.class.php, line:165, function:query, class:MySQLIDatabase, type:->, args:{0:UPDATE item_id SET path=CONCAT('35:/New Folder', SUBSTR(path, 15), level = -1 WHERE path like '35:/NEw Folder/%'}}, 1:{file:/var/www/backend/include/filesystem/ItemIdProvider.class.php, line:122, function:update, class:MySQLIDatabase, type:->, args:{0:UPDATE item_id SET path=CONCAT('35:/New Folder', SUBSTR(path, 15), level = -1 WHERE path like '35:/NEw Folder/%'}}, 2:{file:/var/www/backend/include/filesystem/FilesystemController.class.php, line:717, function:move, class:ItemIdProvider, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [573cafdc69dfd] = 'NEw Folder' (NEw Folder/), 1:FILESYSTEMITEM Folder (LocalFilesystem): [573cafdc69dfd] = 'New Folder' (New Folder/)}}, 3:{file:/var/www/backend/include/services/FilesystemServices.class.php, line:351, function:rename, class:FilesystemController, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [573cafdc69dfd] = 'NEw Folder' (NEw Folder/), 1:New Folder}}, 4:{file:/var/www/backend/include/services/FilesystemServices.class.php, line:35, function:processPutFolder, class:FilesystemServices, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [573cafdc69dfd] = 'NEw Folder' (NEw Folder/)}}, 5:{file:/var/www/backend/include/services/ServicesBase.class.php, line:66, function:processPut, class:FilesystemServices, type:->, args:{}}, 6:{file:/var/www/backend/include/KloudspeakerBackend.class.php, line:85, function:processRequest, class:ServicesBase, type:->, args:{}}, 7:{file:/var/www/backend/r.php, line:81, function:processRequest, class:KloudspeakerBackend, type:->, args:{0:Request}}}
RESPONSE error {0:105, 1:Invalid configuration, 2:403} Error executing query (UPDATE item_id SET path=CONCAT('35:/New Folder', SUBSTR(path, 15), level = -1 WHERE path like '35:/NEw Folder/%'): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE path like '35:/NEw Folder/%'' at line 1`

I think a bracket is missing from the update statement; it works when the names are different as the actual rename creates a new folder so the indexer catches it - the DB still has the old folder in it mind you .... but in the case of just changing the case in a folder name - the folder is inaccessible - i guess someone along the way doesn't care about case but someone does maybe?

seems to narrow down to ItemIdProvider.class.php; line 119 (and I'm guessing the sqlite version two lines up)

Thanks for an awesome system by the way.

**Comment by sjarvela** [comment]
Seems to happen on every folder rename, the update query is malformed. This is related to the query optimization made recently, I'll check this.

**Comment by sjarvela** [comment]
Fixed, closing ")" was missing. You could fix this by simply adding this into line 117 and 119 (see https://github.com/sjarvela/kloudspeaker/commit/04ff2fd3bbb710124083a253814a29f1124d968d)

**Comment by sjarvela** [comment]
Fixed

**Comment by karlneco** [comment]
Thanks
