### ISSUE TITLE
Request failed in file image

### ISSUE THREAD

**Issue by mlarosa63** [sjarvela/kloudspeaker#137]
I use IIS 7.5. The entire installation is ok, no errors. I set up users, groups and folders and I have moved several files, but if I click on image files, I get the failed request message and no tools appears for the file.

![image](https://cloud.githubusercontent.com/assets/18750210/15513899/ddc9c368-21e6-11e6-8395-65b87f40724a.png)

Configuration.php
...
$CONFIGURATION = array(
"db" => array(
"type" => "mysql",
"database" => "sicem",
"user" => "sicem_db",
"password" => "sicem_DB",
"charset" => "utf8",
),
"timezone" => "Europe/Rome", // change this to match your timezone
// "host_public_address" => "http://127.0.0.1", // host public address

"plugins" => array(
    "FileViewerEditor" => array(
        "viewers" => array(
            "Image" => array("gif", "png", "jpg"),
        ),
        "previewers" => array(
            "Image" => array("gif", "png", "jpg"),
        ),
    ),
    "ItemDetails" => array(),
),

"no_dev_urandom" => TRUE,                  // disable PHPPass lib /dev/urandom

"debug" => TRUE,
"debug_log" => "c:/temp/debug.log", // CHANGE THIS
"enable_limited_http_methods" => TRUE,             // limited HTTP methods
);
Nothing in debug.log

Any ideas?

**Comment by sjarvela** [comment]
This sounds like configuration issue. Could you
a) remove setting "debug_log", as it is meant to be used only if you cannot access real PHP error log, and then retry the operation and check PHP logs
b) check browser response

**Comment by mlarosa63** [comment]
This is the error...
[26-May-2016 12:35:41 Europe/Rome] PHP Fatal error:  Call to undefined function exif_read_data() in E:\Siti web\wwwroot\filesmanager\backend\plugin\ItemDetails\ItemDetails.plugin.class.php on line 116

and this is the line in the class
$exif = exif_read_data($item->internalPath(), 0, true);
        if (!$exif) {
            return NULL;
        }

**Comment by sjarvela** [comment]
OK, you are then missing the exif library in PHP: http://php.net/manual/en/book.exif.php

You need to enable/install this first.
