### ISSUE TITLE
Problem with History 1.1 when direct editing

### ISSUE THREAD

**Issue by luke7263** [sjarvela/kloudspeaker#14]
History works fine with all drag/drop and copy operations.
But not when direct editing with integrated text editor. The dates are not correct is the popup. Check picture. And the refresh is not made, so the history count# is not good.
![textedit](https://cloud.githubusercontent.com/assets/11775011/7112541/ecfecebc-e1ca-11e4-8f7e-acd97f3367e2.png)

**Comment by sjarvela** [comment]
2.6.9 has now support for modified metadata, requires also History 1.2 (+DB update)
