### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by mohammadayn** [sjarvela/kloudspeaker#142]
Hi, When I update to last version the download link dose not work anymore, so I had to restore to previous version...

**Comment by sjarvela** [comment]
Could you be a bit more precise. What download link? What is the error?

**Comment by mohammadayn** [comment]
When you want to download a file and click on download button noting happen... There is no error just nothing happen...

**Comment by sjarvela** [comment]
OK, thanks for clarification. Can you check browser console, is there some error visible? Or PHP error log, is there any errors?

**Comment by mohammadayn** [comment]
The error is : "SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 16 of the JSON data" from : "js/kloudspeaker.min.js"
and also tried that with several servers, clients and browsers...

**Comment by sjarvela** [comment]
That is strange, somehow the response from server is not valid JSON.

Could you get the last request response from the browser network inspector? Or would it be possible for me to take a look, is the site public?

**Comment by mohammadayn** [comment]
Sorry but my servers in private network and non of them access to internet.
The request response is : {"result":true}{"result":{"id":"575450754e409","last_changed":"20160309005613","last_modified":"20160214234327","last_accessed":"20160311190935","metadata":[],"permissions":{"filesystem_item_access":"rwd","edit_description":"1"},"parent_permissions":{"filesystem_item_access":"rwd","edit_description":"1"},"plugins":[]}}

It's funny because when I use 2.7.13 there is no problem.
P.S. I use Debian & Ubuntu as my servers.

**Comment by manuel-84** [comment]
i have the same problem after manually upgrading to the last commits (2.7.17 and 2.7.18)

JS error: Unexpected token { in JSON at position 15

Server response:

`{"result":true}{"result":{"id":"574613308bac0","last_changed":"20160525230344","last_modified":"20160525230344","last_accessed":"20160606004108","metadata":{"created":"20160525230344","created_by":"1","modified":"20160525230344","modified_by":"1"},"permissions":{"comment_item":"1","filesystem_item_access":"rwd","edit_description":"1"},"parent_permissions":{"comment_item":"1","filesystem_item_access":"rwd","edit_description":"1"},"plugins":{"plugin-fileviewereditor":{"view":{"embedded":"http:\/\/www.xxx.it\/kloudspeaker\/backend\/r.php\/view\/574613308bac0\/data\/embedded\/?session=1575588234d99d","full":"https:\/\/docs.google.com\/viewer?url=http%3A%2F%2Fwww.xxx.it%2Fkloudspeaker%2Fbackend%2Fr.php%2Fview%2F574613308bac0%2Fcontent%2F%3Fsession%3D1575588234d99d%26_%3D1465223743.1239"}},"plugin-comment":{
`

**Comment by sjarvela** [comment]
OK, I can see the error now.

There is multiple responses, the backend lacks exit point after first response. For some reason some servers/browsers don't mind about this, and so I haven't noticed it.

I've fixed it in https://github.com/sjarvela/kloudspeaker/commit/870fc9e394e4ac1bc44a8791590efc9a03296b3c, you can make the same correction into FilesystemServices.class.php, or wait for the release.

**Comment by sjarvela** [comment]
Released
