### ISSUE TITLE
How to upload a file from direct Linux shell command ?

### ISSUE THREAD

**Issue by luke7263** [sjarvela/kloudspeaker#15]
As a simple cp command line, how to upload a file in a special root folder ?

As for example: 
=> mollifycopy -u username /tmp/srcfile.txt rootfolder:/folder
(would copy the /tmp/srcfile in folder under rootfolder as specified user, no need of password)

**Comment by sjarvela** [comment]
In 2.6.9 there is now initial support for command line interface: https://github.com/sjarvela/kloudspeaker/wiki/Command-line-interface

I will make the documentation better and add more commands etc, but it now shows how different things could be done.

I will also make the Quota plugin refresh into a command that can be run via this interface.
