### ISSUE TITLE
Share Plugin Error: table doesn't get created

### ISSUE THREAD

**Issue by and-jan** [sjarvela/kloudspeaker#153]
I enabled the share plugin in my configuration.php and tried to update the kloudspeaker version under configuration/admin/system in the web interface, but it only said that the latest version is already installed.
Or is something else meant with _Kloudspeaker update util_?

Therefore the `share` table doesn't get created, and I get error messages when I am trying to access the shares that this table does not exist.

Am I missing something?
Or is there maybe a way to manually create the table with the respective attributes?

Thanks!

**Comment by sjarvela** [comment]
For the updater to run, open url "http://yoursite/kloudspeaker/backend/update".
