### ISSUE TITLE
Are there any security updates since mollify?

### ISSUE THREAD

**Issue by alexneventchin** [sjarvela/kloudspeaker#154]
I'm still using mollify ,cuz i like the UI more.My site is using HTTPS , but still - Are there any security updates since mollify? and can i apply them in mollify?

If not ,will you make some?

Thanks.

**Comment by sjarvela** [comment]
Kloudspeaker has been changed quite a bit from Mollify, perhaps not any critical security updates, but mostly the way how UI works.

Mollify is not developed anymore, and any updates to Kloudspeaker cannot be applied directly to Mollify, some changes might be transferrable with little effort, some greater.
