### ISSUE TITLE
Huge requests

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#174]
Every time I click on file or folder and options dialog opens, full user list is downloaded. In my case this is almost 6 megs. This is a huge traffic waste and big problem on slower networks.

Version 2.7.26

**Comment by sjarvela** [comment]
This must be related to the permissions tab, which needs the user data.

I think most straight forward fix is to change the default tab opened, permissions probably isn't the one that needs to be shown first, and this would remove the automatic request.

Then secondarily, perhaps the user data wouldn't have to be downloaded every time, instead use caching etc.

But I'll change the default tab first.

**Comment by sjarvela** [comment]
Fixed in 2.7.27
