### ISSUE TITLE
Invalid FilesystemServices request

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#175]
Every time I click on file icon I get this error:

KLOUDSPEAKER ERROR: ServiceException: INVALID_REQUEST=Invalid FilesystemServices request: POST filesystem/5220adc43f383/info, referer: https://xxxxxxxxxx.com/testing/index.html?v=files/5220ad523f24d
KLOUDSPEAKER ERROR: {0:{file:/home/files/public_html/testing/backend/include/services/FilesystemServices.class.php, line:256, function:invalidRequestException, class:ServicesBase, type:->, args:{}}, 1:{file:/home/files/public_html/testing/backend/include/services/FilesystemServices.class.php, line:65, function:processPostFile, class:FilesystemServices, type:->, args:{0:FILESYSTEMITEM File (LocalFilesystem): [5220adc43f383] = 'Generic.rar' (Wireless/Wireless 3G/Generic.rar)}}, 2:{file:/home/files/public_html/testing/backend/include/services/ServicesBase.class.php, line:69, function:processPost, class:FilesystemServices, type:->, args:{}}, 3:{file:/home/files/public_html/testing/backend/include/KloudspeakerBackend.class.php, line:87, function:processRequest, class:ServicesBase, type:->, args:{}}, 4:{file:/home/files/public_html/testing/backend/r.php, line:81, function:processRequest, class:KloudspeakerBackend, type:->, args:{0:Request}}}, referer: https://xxxxxxxxxx.com/testing/index.html?v=files/5220ad523f24d

Version 2.7.26
Works in version 2.7.23

**Comment by sjarvela** [comment]
This was related to the new (yet) undocumented feature for opening folder hierarchy within file list, and it seems this broke the icon click.

This has been now fixed.

**Comment by sjarvela** [comment]
Fixed in 2.7.27
