### ISSUE TITLE
Huge Error

### ISSUE THREAD

**Issue by alexneventchin** [sjarvela/kloudspeaker#179]
When you log in ---> click CTRL+F5 ----> LOG OUT everything crashes.The wait.gif starts to spin and....

**Comment by sjarvela** [comment]
Could you be more specific, what do you mean with "LOG OUT everything crashes"? You press Ctrl + F5 and then it makes log out? and what is "everything crashes" in details, is there some error or what? Also "and..." meaning, is there something more?

Like always, PHP error log would be nice, pretty difficult to solve anything without some clues.
