### ISSUE TITLE
LDAP authenticated binding, wrong password results in HTTP 500 instead of 403 response

### ISSUE THREAD

**Issue by aplum** [sjarvela/kloudspeaker#187]
When using LDAP authenticated binding, entering the wrong password results in a "Request failed" dialog, HTTP status code 500 and JSON response as follows (i.e. an "UNEXPECTED_ERROR" from the ResponseHandler class):
```json
{"code":999,
"error":"Unexpected server error",
"details":"PHP error #2, ldap_bind(): Unable to bind to server: Invalid credentials (<path_to_kloudspeaker>\\backend\\include\\auth\\AuthenticatorLDAP.class.php:96)",
"data":null}
```

I would expect the response to be "AUTHENTICATION_FAILED" from ResponseHandler (HTTP 403, code 107).

I'm using the following to get the expected response, but I'm hoping you have a better solution.

I replaced line 96 in AuthenticatorLDAP.class.php:
```php
$bind = @ldap_bind($conn, $connString, $pw);
```
with:
```php
$tmp_error_handler = set_error_handler(function() { return true; });
$bind = @ldap_bind($conn, $connString, $pw);
set_error_handler($tmp_error_handler);
```

**Comment by sjarvela** [comment]
You are right, this should really bail out with authentication failure. PHP documentation says the function will return FALSE if it fails, and @ in front should suppress any warnings etc. But this seems to be an "error", not warning or failure, kind of weird behaviour from the api if FALSE is not returned after all...

I suppose this would need that the current global error handler would convert all errors into exceptions (like here: http://php.net/manual/en/class.errorexception.php), and then simply try/catch it here.

Unfortunately I don't working LDAP setup right now, would you be able to help test this theory.

This would require changing r.php function "globalErrorHandler" to simply something like this:

    function globalErrorHandler($severity, $message, $file, $line) {
        throw new ErrorException($message, 0, $severity, $file, $line);
    }

and then in AuthenticatorLDAP.class.php from line 95:

			Logging::logDebug("Authenticating with LDAP: ".$connString);
			try {
				$bind = @ldap_bind($conn, $connString, $pw);
				if (!$bind) {
					Logging::logDebug("LDAP error: ".ldap_error($conn));
					return FALSE;
				}
			} catch (Exception $e) {
				Logging::logDebug("LDAP error: ".ldap_error($conn)."/".$e->getMessage());
				return FALSE;
			}

**Comment by aplum** [comment]
I reverted my change, then applied the two code snippets you provided for r.php and AuthenticatorLDAP.class.php, and it's working as expected. Is there more testing I should do, or anything further I can do to help?

**Comment by sjarvela** [comment]
No, this is enough for me, I will add this into the next release. Thanks for the help!

**Comment by aplum** [comment]
I just updated my installation to v2.7.30 and this issue seems to be fixed. Thanks!

**Comment by s31t0n** [comment]
Hi Aplum,
would you be so kind to share the LDAP configuration files?
Thanks in advanced.

**Comment by aplum** [comment]
Sure. I'm using the following in `configuration.php` for Active Directory (Windows Server 2012 R2).

```php
"authentication_methods" => ["pw", "ldap"],
"ldap_use_starttls" => true,
"ldap_server" => "dc1.ad.something.tld",
"ldap_conn_string" => "@ad.something.tld",
```

Then when adding a user (e.g. the Active Directory user `aplum@ad.something.tld`) in Kloudspeaker, fill in `Username: aplum` and `Authentication: ldap`. Password can be left blank. Also note that the machine hosting Kloudspeaker will need to trust the certificate of the `ldap_server`.

**Comment by s31t0n** [comment]
Thanks a lot Aplum,
the config helped me a lot, but still getting some errors a guess its because of the trusted certificate
`**RESPONSE error {0:107, 1:Authentication failed, 2:403**`
Could you be so nice to share the steps no how to trust the certificate correctly on my mac?

Thanks again for your kindness.

**Comment by aplum** [comment]
Sorry s31t0n, but I'm afraid I can't help you there. My setup was on a Debian machine, and I haven't worked much with certificates on Macs. Good luck!

**Comment by aplum** [comment]
In case anyone comes across this thread in the future, I've continued this in #199.
