### ISSUE TITLE
Drag and Drop Folder

### ISSUE THREAD

**Issue by keikers** [sjarvela/kloudspeaker#189]
I would like to know if it will be possible and how to drag and drop a whole folder remaining the structure with subfolders and contents, and not copying only the contents of folder.

For example: 
Parent folder : Test
Subfolder : Test1
Subfolder's content : Test1.pdf, Test2.pdf
Subfolder : Test2
Subfolder's content : Test3.pdf, Test4.pdf

I want to drag and drop Parent folder "Test" and copy subfolders and contents!

**Comment by sjarvela** [comment]
At the moment, operation is based on the source and target. If items are moved inside same root, then it is a move operation.

I did consider making a way to choose this when making the operation (perhaps with Shift-Key or something, if this is possible), but now there is no way.
