### ISSUE TITLE
File Upload Size Limits

### ISSUE THREAD

**Issue by lonn-u** [sjarvela/kloudspeaker#19]
When uploading a file, if the file is larger than the limit set in php.ini, the upload fails and the following message is displayed: "File upload failed".  This message is not really very helpful.  

My suggestion:  When loading the app, get the upload limitations imposed by php.  Use this to compare against the file size before uploading and present an error if it's too big.  You'd also have to compare against the maxChunkSize for the uploader.

**Comment by Supernut101** [comment]
ok, this has been annoying me for a while. no one on any site talking about the max upload limits tell me where the actual config files that I need to change are... I know where php.ini is but I cant find anything regarding the uploader. I keep getting the upload failed error and only wish to allow bigger files to be uploaded. i have already set my php.ini

**Comment by sjarvela** [comment]
I added description for the settings here: https://github.com/sjarvela/kloudspeaker/wiki/Uploader

The original issue is still valid, I'll investigate the error message.

**Comment by sjarvela** [comment]
File size exceeded error now detected in latest release, but it seems it might not be 100% waterproof (PHP does not inform this clearly, it needs to be determined based on few things that may or may not work in different servers).
