### ISSUE TITLE
updated to 2.6.8 how to see that actually on 2.6.8

### ISSUE THREAD

**Issue by mrjohnpoz** [sjarvela/kloudspeaker#21]
So update went smooth, and know on the latest version because the new ignore file type is working but is there anywhere to actually see info about the install, like version, maybe some items out of the configuration file like database, etc.

I don't see an about anywhere, would be nice to be the configuration menu maybe?

**Comment by sjarvela** [comment]
It can be seen in the "backend/include/Version.info.php", but sure, I'll add it somewhere visible in the UI as well.

**Comment by sjarvela** [comment]
Released in 2.6.9

**Comment by mrjohnpoz** [comment]
so updated to 2.6.9 - where is it in the UI?  Not seeing it.. Figure there would be say an about in the configuration area..

**Comment by sjarvela** [comment]
It's in Configuration->Admin/System

**Comment by mrjohnpoz** [comment]
Doh! ;)   Nice check for update as well - thanks!
