### ISSUE TITLE
webdav?

### ISSUE THREAD

**Issue by mrjohnpoz** [sjarvela/kloudspeaker#22]
So what account actually can auth?  How do you setup auth.. I placed the files where they are suppose to go..  I hit /backend/dav with browser but auth doesn't work.

says defaults to digest - is there something else need to setup?

I don't see anything in configuration about having to enable the plugin in configuration.php, etc.

**Comment by sjarvela** [comment]
You should use basic auth, it's currently the only way.

Digest auth is better than basic auth, but since I introduced proper password handling with hashing and salting, it is not possible anymore. Digest relies on MD5 hashing, which is not secure, and would require having plain text password at hand, and this is why it is not possible anymore. With password management based on hash and salt, there is no way to resolve the original password (this is what makes it secure).

It seems BASIC_AUTH default value is left to FALSE, I changed this now. I haven't removed the digest option as I'm going to investigate if there is a way to overcome/rewrite the auth mechanism somehow.

**Comment by mrjohnpoz** [comment]
even if I enable basic it does not auth with my admin account, etc. Where are the instructions for using this?  I don't see it mentioned anywhere in the wiki.  TIA

**Comment by sjarvela** [comment]
The instructions have been in ReadMe.txt, but I just added the page at: https://github.com/sjarvela/kloudspeaker/wiki/WebDAV-plugin

Try setting
$ENABLE_BROWSER = TRUE;

This allows testing with browser. If this does not work, then use debug logging to see what is the error.

Real WebDAV clients should not be used until browser client is working.

**Comment by sjarvela** [comment]
Did some research, and it is a fact that when strong password hashes are used, digest auth is not an option (http://en.wikipedia.org/wiki/Digest_access_authentication).

Digest auth is very old, designed back when HTTPS was not yet standard, and it was meant to solve the problem with basic auth sending passwords in clear text via regular HTTP connection. But digest itself is weak, and thus Basic auth via HTTPS is commonly considered far better alternative, as it allows using any password strategy (the fact that password is sent in clear text is no problem when the connection is secured to begin with).

Therefore digest auth is removed in next release of webdav plugin.

**Comment by nnmalex** [comment]
I was able to log in via WebDav both via browser and via WebDav client but I can't upload/create anything, I see empty folder and can't understand what folder is it. Can I define the root folder for WebDav access?

**Comment by sjarvela** [comment]
When logging in via WebDAV, you should first see all the same root folders you see in web client UI in the left side panel. This first level is not writable, it is supposed to list only the folders that has been shared for the user, so you cannot create folders there (ie. it's kind of a virtual folder).

With browser, first there should be a page with title "Index for /", and list of shared folders where you can click them to go into one. If you don't see anything (but there are folders listed in web UI), then something is wrong.

You should

a) make sure you use correct user when logging in, ie same as with web client

b) check your webdav index.php that you have correct values for KLOUDSPEAKER_BACKEND_ROOT and BASE_URI (explained in ReadMe.txt)

c) enable debug logging and then try opening webdav page in browser, and see if there are any errors in the log (note that webdav may generate lots of log, so remember to disable it afterwards)

**Comment by nnmalex** [comment]
Tried again on 2.7.3 and it worked fine for me this time. Solved for me. Thanks.

**Comment by sjarvela** [comment]
Glad to hear!
