### ISSUE TITLE
Sharing entire folders for downloading

### ISSUE THREAD

**Issue by firlevapz** [sjarvela/kloudspeaker#25]
It would be nice to share an entire folder via public link-sharing for downloading (also with the option to compress certain subfolders or the entire shared folder for downloading). 
Additionally to share a collection of files with the option to view them before downloading them entirely as a zip-file would be great!

**Comment by nnmalex** [comment]
Sharing a folder with ability to download it as a zip archive would certainly be very nice.

**Comment by sjarvela** [comment]
Definitely. Right now I'm rewriting the plugin client to AMD modules, after which it is easier to improve it.

**Comment by sjarvela** [comment]
This was added in 2.7

**Comment by CNG** [comment]
Forgive me for being new to Kloudspeaker… but how do you make this feature work? I navigate to a folder in the admin and generate a share link for the item "FOLDER NAME" ... but when I try the link in another browser, I just get the "upload files to FOLDER NAME" screen.

When I don't use "Quick Share", the popup with the options specifies "Upload to folder" as the share type, and I cannot change it.

**Comment by sjarvela** [comment]
You need to have archiver plugin enabled, and after that you have an option to choose share type as "download compressed"

**Comment by CNG** [comment]
Thank you for the reply. I've enabled the "Archiver" plugin, and it did add a "Download compressed" option in the back end / admin view. However, my goal is to share a link to a folder and have unregistered / anonymous users viewing the link be able to see the files in the folder. Downloading them as a ZIP is a nice bonus, but not even my goal.

As it stands, I've installed the software and enabled "Share" and "Archiver" in addition to the already enabled "FileViewerEditor" and "ItemDetails" plugins. When I generate a link to share a folder, viewing it in another browser not logged in (emulating the person I would share the link with), I get a screen with only this:

> Upload files to "articles"
> 
> Click the button to select uploaded files, or drag&drop files here
> 
> [button]

Is it possible to share an entire folder with public? Otherwise I should go back to default Apache index page… that's the reason I tried this software. Thanks!

**Comment by CNG** [comment]
I just noticed the "Archiver" plugin added a "Share Type" of "Download folder compressed", so it seems I can now share a link to download the entire folder. Still, I cannot use this for my purpose of sharing a folder in a way the user can view the files in it and choose which ones to download. I am basically looking for exactly what the Apache or Nginx automatic folder index page shows… just a list of files in the folder that is updated when the link is opened. Is this possible? Perhaps there is another plugin I need to add a "Share Type" of "View files in folder"?

**Comment by sjarvela** [comment]
Unfortunately this does not yet exist. It's been on my list, but haven't had time for it yet. Share type "Browse files" would require some kind of dynamic guest session, where the guest has read permissions to only that one folder he opened the link for.

**Comment by CNG** [comment]
Ah, I see. Well thank you for clearing that up. I understand finding time is hard, so I can't complain!

**Comment by sjarvela** [comment]
Actually, I think using separate view for guests would be better anyway, so this might not be too difficult.

The first idea was that guests would use the same UI for browsing, only with restricted permissions, but in this case it's not a good idea, as the UI is meant for logged in user, most of the things would be meaningless in this case (like top bar, which has "files", "configuration" and log out, as well as left side navigation etc)

**Comment by CNG** [comment]
Well, if it would be easy-ish to point me in the right direction, perhaps I can take a crack at it. I am not (yet) familiar at all with this software package, so at this point I don't know if it would be worth me trying to figure it out and submit a patch. Let me know what you recommend. I'll stick with basic Apache indexes for now… it's be cool to get some of the statistics and download as ZIP features though!

**Comment by CNG** [comment]
Hello again. I reviewed the change log since a year ago and did not see anything related to a "browse files" share type with guest sessions (anonymous, unregistered, public access to folder). If I missed it and it exists now, please let me know. Otherwise no worries, thanks!
