### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Pingblue** [sjarvela/kloudspeaker#29]
I installed Kloudspeaker successfully but there doesn't appear to be a login page.

**Comment by hakimam** [comment]
Hi, 
I happened to have installed kloudspeaker today and I can see the login page only with Firefox but not with Safari nor Chrome for which I get a blank page. 
Seems there is a problem with kloudspeaker/js/kloudspeaker.full.min.js (see attachement) which prevents the page to be loaded properly. 
![problem_kloudspeaker](https://cloud.githubusercontent.com/assets/1765453/7982063/0149e110-0ab4-11e5-930a-286db78b61ba.png)

**Comment by Pingblue** [comment]
What is the actual address of the login page?

**Comment by hakimam** [comment]
http://pao.archeo-lattes.cnrs.fr/kloudspeaker/

**Comment by Pingblue** [comment]
So the problem with my install is I have no index.html

**Comment by hakimam** [comment]
To be more accurate, the error in the javascript file prevents the creation of a proper index file

**Comment by sjarvela** [comment]
To be precise, javascript certainly does not create index files, it is the index.html that loads the javascript. But sure, if there is an error, it may prevent from page loading.

Is there a site I could access to see the error myself? Or alternatively, switch into "kloudspeaker.full.js" (ie. remove the "min") in index.html to see more accurate error and line number

**Comment by Pingblue** [comment]
When I try to install with the git clone version there is no login page but if I download from the kloudspeaker domain it works.

**Comment by sjarvela** [comment]
Git clone downloads the development package, not installation package. The installation package is created with grunt script, which combines and minifies js and css resources etc.

If you setup development tool, you could of course build the installation package as well.
