### ISSUE TITLE
Cannot Run Update

### ISSUE THREAD

**Issue by Texxy38** [sjarvela/kloudspeaker#32]
Hello, 
In the documentation, you mention several times that when a plugin is installed (like share), we should run the update util after we performed the modification.
How can I run the update utility ?
I tried to access to the /backend/update/index.php but it says that nothing needs to be updated and my changes are not taken into account...
Is there something I missed ?

Many Thank and sorry for the possible dummy request...

**Comment by nnmalex** [comment]
I had this question as well.

You have to unpack the plugin into appropriate folder and “activate” it in index.html and backend/configuration.php according to plugin's manual.

Once the above done correctly update script you mentioned will see there is something to update.

**Comment by sjarvela** [comment]
Plugins are installed in the application installation as well, if they were listed in the config. But if they are added into the configuration after installation, then you need to run updater.

Plugin registration is in configuration.php, but some plugins may have also client plugins that are registered in index.html. But this is changing, with the plugins written in AMD modules (few has been rewritten, more coming later) client modules are loaded automatically.

**Comment by Texxy38** [comment]
Thank you for the answers...
The one I try to add is the Archiver Plugin.
I modified both frontend index and backend configuration, but when I try to update, still shows that "No Update is required".
Wonder how you run an update ? Simply goes to /backend/update ? or anything else to be done ?

I work on a normal version to which I try to add the common plugins.
I can see there is something missing because when I now goes into the KS frontend, when I try to display the context menu over a file the system keeps looking for something and doesn't display the menu anymore...
I assume there is something wrong in the way I do, but can't figure what it is...

**Comment by sjarvela** [comment]
Yes, updater requires only "backend/update"

But some plugins don't have anything to install, and all that is required is just to register it. Plugin wiki page should state if running updater is required.

Archiver does not have database, and so it does not need installer.

**Comment by sjarvela** [comment]
I'll close this as it seems there is no error in the update process. Of course, if there is something to add into documentation, let me know what would help?
