### ISSUE TITLE
Trashbin with sqlite error

### ISSUE THREAD

**Issue by gitfabfab** [sjarvela/kloudspeaker#35]
Using sqlite as backend storage, the following error occurs when trying to enable the trash bin plugin:

Update failed
Error reading sql file (plugin/TrashBin/sqlite/install.sql)

**Comment by sjarvela** [comment]
Unfortunately sqlite version of the install script haven't been added, I'll add this in next release.

**Comment by sjarvela** [comment]
was added in 2.7
