### ISSUE TITLE
User creation mail notification

### ISSUE THREAD

**Issue by nnmalex** [sjarvela/kloudspeaker#40]
Is it possible to send automated email upon user creation (from admin panel) to the email specified in the newly registered user profile?

**Comment by sjarvela** [comment]
No. It is possible to send email for user creation event, but at the moment it is not possible to use the user itself as recipient.

At the moment it can take only predefined users or groups, but it would be indeed be useful to have possibility to send email to whoever performed the action.

**Comment by nnmalex** [comment]
I didn't mean sending notification to the user creator. I meant user Admin creates user User1 with email user1@example.com and system sends an email to user1@example.com to notify a person that he has been given an account.

**Comment by sjarvela** [comment]
OK, got it. However, same thing preventing this, notifications can be given only static recipients, ie it's not possible to say "use recipient from event data X", where data here would be the created user.

The biggest problem here would be that different events have different data, other events don't have "created user" info, so how would this be defined in the notificator system?

**Comment by nnmalex** [comment]
I wish I could advise on how to implement this. 

But that would be a nice feature to have.

**Comment by sjarvela** [comment]
So far I haven't come up with good solution, building some kind of special case for "user created" event sounds like overkill, and cannot figure out other cases where mail recipient would be resolved from the actual event.

I was thinking adding some kind of dynamic recipient system, where different event types would bring different dynamic recipient options available. Ie. "user created" event would enable choosing dynamic recipient called "created user" etc, but like I said, I cannot figure out other use cases.

As an alternative, I was thinking building this feature as some kind of special configuration option, like "notify created user", and if enabled, could send some predefined message to the created user.

Have to give this some more thought.

**Comment by nnmalex** [comment]
The project is clearly dead.
