### ISSUE TITLE
Uncaught ReferenceError: session is not defined

### ISSUE THREAD

**Issue by marino-mrc** [sjarvela/kloudspeaker#41]
Hi, I installed kloudspeaker on centos 6.5 with apache web server following instructions in the wiki and I have a js error "session is not defined" when I try to upload a file (as admin user). I'm trying with firefox and chrome on lubuntu and I have the same behavior. Someone can help me please?
Thanks

**Comment by sjarvela** [comment]
This dependency flaw has been fixed, will be in next release. I may release fixed js file sooner if release takes more time.

**Comment by sjarvela** [comment]
Could you try with this version (added in the release): https://github.com/sjarvela/kloudspeaker/releases/download/v2.6.15/kloudspeaker.full.min.js

**Comment by marino-mrc** [comment]
It works! Thank you and sorry for the delay.
MM

2015-08-21 10:54 GMT+02:00 sjarvela notifications@github.com:
