### ISSUE TITLE
File Download impossible with IE 11, Firefox and Edge

### ISSUE THREAD

**Issue by Telebear** [sjarvela/kloudspeaker#42]
Download a selected File is not possible with with IE 11, Firefox and Edge. Crome works.

Error Message in web console:
 "fs" ist undefiniert" (fs is undefined) kloudspeaker.full.min.js, line: 25, column: 20349

Kloudspeaker 2.6.15 (rev. 27)
Latest Version of Firefox,IE 11 and Edge

**Comment by sjarvela** [comment]
See https://github.com/sjarvela/kloudspeaker/issues/41
