### ISSUE TITLE
Problem for uploading files from the browser.

### ISSUE THREAD

**Issue by ghost** [sjarvela/kloudspeaker#44]
When I try to upload a file, select the file with the tool and I click OK, but the file is not loaded.

If I try twice in a row the file is loaded.

And checked if a permissions problem and everything seems to be correct. Please note that the file is uploaded when I try twice.

Any ideas ?

**Comment by ghost** [comment]
ExtraInfo: You can not delete uploaded files.

**Comment by sjarvela** [comment]
See issue 41: https://github.com/sjarvela/kloudspeaker/issues/41

Try with the new version of js, should fix uploading. Don't see any problems with deleting, so might be related.
