### ISSUE TITLE
Confirm share download with a button

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#46]
It would be good if public share download would only start after clicking "download" button and not immediately as it is now. This would make kloudspeaker more compliant with Google's Unwanted Software Policy https://www.google.com/about/company/unwanted-software-policy.html : 
"Download of the software should only begin when the user has consented to the download by clicking on a clearly-labelled download button."

**Comment by nnmalex** [comment]
I agree. It would also help if you create the link and want to check it not downloading the file.

**Comment by sjarvela** [comment]
I agree

**Comment by sjarvela** [comment]
First version committed (https://github.com/sjarvela/kloudspeaker/commit/ed8a10812339154312c4c9fd37ddfa589284dee0), will be in next release

**Comment by sjarvela** [comment]
in 2.7.3
