### ISSUE TITLE
After upgrade passwords no longer work

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#47]
We did an upgrade/migration from Mollify 2.1.6 -> 2.6.7 -> Kloudspeaker 2.6.15 and passwords does not work any more. In the AuthenticatorPW.class.php support for legacy passwords is missing.

**Comment by sjarvela** [comment]
Like the migration page (https://github.com/sjarvela/kloudspeaker/wiki/Migration-from-Mollify) says, you need to add the server salt to the configuration, because the default one is changed in the transition (the passwords are generated with Mollify default salt, so you need to use the same salt).

**Comment by VytisG** [comment]
I did that. There are no problems with the new users. They can login just fine, but not the users created before migration. In 2.6.15 there are no getUserLegacyPw calls.

This works: update to 2.6.7 -> login -> update to 2.6.15 -> login
This does not: update to 2.6.7 -> update to 2.6.15 -> login

**Comment by sjarvela** [comment]
New users of course work, because they are generated with the "right" salt. But are you certain your configuration.php is correct, because this problem does sound exactly like the salt is not restored. 

However, if you now change your salt, your newly generated users don't work anymore.

If there are not that many users, you could use either lost password plugin to recreate passwords, or admin user could reset them manually.

**Comment by VytisG** [comment]
I do not think that in 2.1.6 was such thing as salt, so "restored" is not a correct way to say. 

Well, I cant force 24k users to reset their passwords, or do it manually :)

Adding if ($auth["salt"] == "-" and $auth["hash"] == "-") {...} back to Kloudspeaker_Authenticator_PW solves the problem.

**Comment by sjarvela** [comment]
I meant restoring the server salt setting.

But yes, didn't realize you had version prior to password hashing. Mollify had "lazy" password upgrade method, creating new password hashes whenever it encountered legacy passwords. In Kloudspeaker it was assumed that passwords are always generated with new hashing method, and thus the legacy support was removed.

Glad you found the solution yourself, perhaps I should document this into migration page, as I don't think I'm gonna keep such legacy functionalities when they are never needed in this product branch.

**Comment by VytisG** [comment]
Yes, that would be a great idea.

**Comment by sjarvela** [comment]
Migration page updated
