### ISSUE TITLE
Offline viewer for pdf files

### ISSUE THREAD

**Issue by marino-mrc** [sjarvela/kloudspeaker#48]
Reading the wiki: "Using Google Viewer requires that files can be accessed from internet (as the Google service needs to download the file). When Kloudspeaker is used in a closed network (ie. intranet), this viewer cannot be used."
So, how can I use the pdf preview in a closed network?
Thank you

**Comment by sjarvela** [comment]
The problem has been, that there is no, at least I haven't found, decent pure PHP library that can do PDF to image conversion (this is ultimately what is required to display PDF in browsers).

There has been few libraries that use some native tools or exec calls to process PDF files, but these are not acceptable.

Just googled this again, and found this: https://github.com/spatie/pdf-to-image

I'll have to test this to see if it works, but any suggestions are welcome

**Comment by sjarvela** [comment]
Also, note that many browsers, like Chrome, can display PDF files by themselves, so using a direct viewer is an option:

```
    "FileViewerEditor" => array(
        "viewers" => array(
            "Direct" => array("pdf")
        ),
```

Of course, if browser does not know what to do with it, it will download it, so this is not bulletproof unless you can be sure users have certain browser.

**Comment by marino-mrc** [comment]
Why not use a jquery pdf viewer (pdf.js is just an example....) ?

2015-09-01 10:15 GMT+02:00 sjarvela notifications@github.com:

**Comment by sjarvela** [comment]
Thanks for the tip, pdf.js was unknown to me.

It is certainly interesting, but reading the project page (https://github.com/mozilla/pdf.js), there are many browsers that don't do very well, like Safari, and it also requires installing an extension.

Edit: no I misunderstood the extension. Extensions are included in the library, so browsers will pick them there. But still, not a bulletproof option, although best so far.

**Comment by sjarvela** [comment]
I've added draft version of ViewerJS into viewers (will be in next release), it kind of works but not fully. First the default layout does not fit the embedded mode (bottom toolbar is left under the overlay), and also I've found that pdf.js does not seem to support all PDF file versions. But anyway, it's there as an option in next release.

**Comment by sjarvela** [comment]
ViewerJS draft available in 2.7.3

**Comment by marino-mrc** [comment]
Thank you. I will give a try this week

**Comment by mileper2nd** [comment]
Hy, I can't figure out if ViewerJS draft can display pdf file in intranet network and how could I enable it?

**Comment by sjarvela** [comment]
Yes it can, assuming it is able to read the file (there are some limitations). There were some console errors when I tried it, I should update the ViewerJS version to see if they are fixed.

**Comment by sjarvela** [comment]
Updated in earlier release
