### ISSUE TITLE
Way to hide file types?

### ISSUE THREAD

**Issue by mrjohnpoz** [sjarvela/kloudspeaker#5]
Is there a way to not show some file types, for example .txt or .php not to show those files that might be in the path where other files are shown.

**Comment by sjarvela** [comment]
I've now added support for defining rules what to ignore. Settings can have a list of regex patterns that allows ruling out any items globally or specifically in a certain path.

**Comment by sjarvela** [comment]
Released in 2.6.8.

You can now define ignore rules with configuration setting:

"ignored_items" => array("/.pdf$/i")

which would ignore all PDF files anywhere. The value is regex pattern, I'll add wiki instructions later.

**Comment by sjarvela** [comment]
Configuration documented here: https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#ignored-filesystem-items-ignored_items

**Comment by mrjohnpoz** [comment]
sweet can not wait to update to this version and give it a try.. I would like to hide the .meta files from the listing..

**Comment by mrjohnpoz** [comment]
This works perfect, thanks!
