### ISSUE TITLE
Multiple bugs in 2.7

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#50]
KLOUDSPEAKER ERROR: PHP error #8, Undefined variable: size (/home/files/public_html/backend/include/filesystem/FilesystemController.class.php:1166)

Uncaught TypeError: app.showFullView is not a function in access_password.js:39

In the KloudspeakerExternalInterface.class.php, addUserToGroup() function "!" is missing. 
Should be $g = !is_array($gr) ? array($gr) : $gr;

**Comment by sjarvela** [comment]
I'll take a look and fix in 2.7.2

**Comment by sjarvela** [comment]
Fixed in 2.7.2
