### ISSUE TITLE
2.7.1 (rev. 29) fails to initialize in Spanish

### ISSUE THREAD

**Issue by JaimeObregon** [sjarvela/kloudspeaker#51]
On a fresh install, when `language.default` is set to `es`, KloudSpeaker 2.7.1 fails to start with `Failed to initialize Kloudspeaker` error.

English, French, Hungarian and German languages are not affected. `localization/texts_es.json` is present and fetched by the browser. The JSON language file is valid (according to jsonlint.com) Reproduced in both latest Firefox and Chrome.

Thank you for your time in this useful piece of software!

**Comment by sjarvela** [comment]
It was a mistake in the first line, the language code was "en". Fixed version is shipped with 2.7.2
