### ISSUE TITLE
Admin shares bug in 2.7.2

### ISSUE THREAD

**Issue by VytisG** [sjarvela/kloudspeaker#52]
Administrator can not edit not his own shares. Browser returns error:

Uncaught TypeError: Cannot read property 'share' of null in /backend/plugin/Share/client//repository.js:14

**Comment by sjarvela** [comment]
In what case do you see this error, quickly trying this does not give me any errors? Can you give me exact steps so I can reproduce it?

**Comment by VytisG** [comment]
I go to Configuration -> Admin -> Shares and click on edit icon. If share is my own, I get window with Shared item, Name, etc. fields filled in. If share was created by some other user, I get window with all the fields empty.

**Comment by sjarvela** [comment]
That's correct, server side did not give share information for users other than who owns it, even not for admins. Fixed in 2.7.3
