### ISSUE TITLE
Unable tu create new users when `/dev/urandom` is not accessible

### ISSUE THREAD

**Issue by JaimeObregon** [sjarvela/kloudspeaker#53]
Kloudspeaker latest (2.7.2) fails to create a new user when `/dev/urandom` is not accessible to PHP due to `open_basedir` restrictions. The action will fail with a generic error message (which I don't provide because I'm using a translated version; giving an additional error code would be useful in the future for this purpouse).

When creating a new user I'm getting the following message embeded in the `detail` property of a JSON response:

```
PHP error #2, is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/xxxxxxxxx.es/:/tmp/) (/var/www/vhosts/xxxxxxxxx.es/yyyyyyyyyyyyyy/backend/vendor/phpass/PasswordHash.php:78) 
```

As I don't want to fiddle with my `open_basedir` configuration, which I consider valid, I have commented the following lines in `PasswordHash::is_devurandom()`, which solved the issue for me:

```
function is_devurandom() {
        if (Logging::isDebug()) Logging::logDebug("/dev/urandom: ".($this->no_devurandom ? "0" : "1"));
        if ($this->no_devurandom) return FALSE;
        if (Logging::isDebug()) Logging::logDebug("Trying /dev/urandom");
//      try {
//              if (@is_readable('/dev/urandom')) return TRUE;
//      } catch (Exception $e) {}
        if (Logging::isDebug()) Logging::logDebug("/dev/urandom not accessible");
        return FALSE;
}
```

**Comment by sjarvela** [comment]
Try this option: https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#disable-devurandom-access-no_dev_urandom
