### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by rodolfoleo** [sjarvela/kloudspeaker#55]
Dropbox doesn't work. Tested in Safari and Chrome in Mac OS X 10.10.5. I installed the "Item collection plugin" as I thought it would activate the functionality, but it didn't. All other plugins I installed run correctly. Thanks.

**Comment by sjarvela** [comment]
Exactly what is not working, it does not show at all, or some function does not work? I just fixed error for adding files to list, it is fixed now.

If you want to fix your version, open "kloudspeaker.full.min.js" and search for "window.isArray" (should be one match), replace it with "utils.isArray".

**Comment by sjarvela** [comment]
Required some more fixes, available in 2.7.3

**Comment by rodolfoleo** [comment]
The dropbox slides from the right side of the page but I can't add any items to it, not even with the "item collection plugin" installed. I just applied the change you mentioned but there's no change in the behaviour.
