### ISSUE TITLE
Archiver

### ISSUE THREAD

**Issue by jaliwolf** [sjarvela/kloudspeaker#56]
I have a problem when i want to install the plugin Archiver, the error is:

Parse error: syntax error, unexpected '"enable_download"' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in C:\wamp\www\sigedo\backend\configuration.php on line 32
Call Stack
# Time    Memory  Function    Location

1   0.0014  267640  {main}( )   ..\index.php:0

Can I help me please.

**Comment by jaliwolf** [comment]
This the code copied:
"Archiver" => array(
            "compressor" => "[COMPRESSOR]"
            "enable_download" => TRUE/FALSE,
            "enable_compress" => TRUE/FALSE
            "enable_extract" => TRUE/FALSE
        ),

**Comment by sjarvela** [comment]
To start with, you are missing commas from end of lines, corrected this into wiki page.

But you are not supposed to copy&paste the example as it is, you need to put real values there according to the wiki instructions (and are not mandatory, they have default values).

**Comment by jaliwolf** [comment]
Can you show the wiki about Archiver or the link about it...

**Comment by jaliwolf** [comment]
i when install the plugin archive the opcion is able, but wanto to compress a file o folder i show a error: Request failed.

The code en mi page cofiguration.php is.

 "Archiver" => array(
        "compressor" => "[COMPRESSOR]"
        ),

Is correct? What is the problem?

Thank you

**Comment by sjarvela** [comment]
The "[COMPRESSOR]" is just a placeholder, you should put a value in there instead. Wiki is here: https://github.com/sjarvela/kloudspeaker/wiki/Archiver-plugin

And for any "request failed", please take a look at php error log
