### ISSUE TITLE
video viewer does not work

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#58]
Hi,

After download and extracted JPlayer into viewer folder and enabled it in configuraiton.php.
Everything seems to be fine, however, it just does not play the file at all.
But if I extracted the file url from palyer and access it directly from Chrome, chrome plays it without any issue.
File is a mp4 video.

Cheers,
Jason

**Comment by sjarvela** [comment]
FYI, it is not JPlayer that is supposed to show video, but FlowPlayer.

Just tested myself, and for some reason I could not make it play a video either. Player itself did not give any errors etc, my development environment has been erased so old test clips are gone also.

But the FlowPlayer was quite old, so I updated the version into 6, and it seemed to work.

You can browse (and probably also download) the committed version with commit tag: https://github.com/sjarvela/kloudspeaker/tree/55df4c0aac61c6397a2a15f1a9cdc6cf838e5596/backend/plugin/FileViewerEditor/viewers/FlowPlayer

**Comment by jasonPaddy** [comment]
Thanks for the prompt fix.I have tested it, it can play the file now.

However, there are two additional bugs I found.
1. video timeline is not seek-able which I believe it is probably related handling byte-range requests
ref: http://stackoverflow.com/questions/3128906/mp4-plays-when-accessed-directly-but-not-when-read-through-php-on-ios 
1. when it finished playing, click play button, it throw an error
   html5: Network error
   http://192.168.97.10/kloudspeaker/backend/r.php/view/55ff99c1edcc6/content/?session=15600930b2c171&amp;_=1442883847.9362

Cheers,Jason Gu

---- On Mon, 21 Sep 2015 23:34:06 +1000 sjarvela&lt;notifications@github.com&gt; wrote ---- 

FYI, it is not JPlayer that is supposed to show video, but FlowPlayer.
 Just tested myself, and for some reason I could not make it play a video either. Player itself did not give any errors etc, my development environment has been erased so old test clips are gone also.
 But the FlowPlayer was quite old, so I updated the version into 6, and it seemed to work.
 You can browse (and probably also download) the committed version with commit tag: https://github.com/sjarvela/kloudspeaker/tree/55df4c0aac61c6397a2a15f1a9cdc6cf838e5596/backend/plugin/FileViewerEditor/viewers/FlowPlayer

**Comment by sjarvela** [comment]
Byte range support is there, but it isn't used.

When I tested timeseeking, it always restarted playback from the start, it never even tried to get byte-range. If you have something in the error log related to this, please let me know.

Also, for the error you have after finished playing, I don't have this. Anything in the error log?

**Comment by jasonPaddy** [comment]
Hi Sami,
Thanks for the reply.
Not sure what you meant of below comment,
'Byte range support is there, but it isn't used.'
do you mean that flow player is not using byte range?

**Comment by sjarvela** [comment]
Actually, I found out that it really makes one request with byte range "0-", which means "give me all". And after that, it does not make any requests, no matter what happens.

But it occurred to me that this, of course, could be due to too short clip, I'd have to seek for longer test clip. If you have a link to some public mp4 clip that lasts for at least 10 mins or so, let me know.

It also occurred to me that byte range support may not be supported in viewer API, so this have to be tested once I get a longer clip.

**Comment by jasonPaddy** [comment]
you can pick a mp4 from below url:
http://download.blender.org/peach/bigbuckbunny_movies/

just did another test. I can confirm issue is in viewer's API or php script

play below in Chrome without FlowPlayer resulted same issues.
source src="http://192.168.97.10/kloudspeaker/backend/r.php/view/55ff99c1edcc6/content/?session=1560245fed9cf6&amp;_=1442989678.2072" type="video/mp4">
<source src="http://192.168.97.10/background_video_01.mp4" type="video/mp4">

if I play the same file directly from http, it works as expected, seek timeline. replay etc.
http://192.168.97.10/background_video_01.mp4

**Comment by sjarvela** [comment]
Of course you cannot compare native browser viewing with FlowPlayer viewing, they have very little common. But I'll test with that clip.

**Comment by sjarvela** [comment]
Like I suspected, range was not supported in view API, and it is now added: https://github.com/sjarvela/kloudspeaker/commit/adf6d3068e694e29bb1db2fbbfb056f085e05598

For me, I was able to also seek with no problems, but I'll have to test it a bit more.

**Comment by sjarvela** [comment]
Released in 2.7.4
