### ISSUE TITLE
double attachments when upload file using drag and drop

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#59]
version: 2.7.3
Browser: Chrome Version 45.0.2454.93 (64-bit)

duplicated attachments when uploading file using drag and drop feature.
below error is observed when this happens. but this error is not showing up every time though.

POST http://192.168.97.10/kloudspeaker/backend/r.php/filesystem/55ff94f8215c0/files/?format=binary 403 (Forbidden)ia.ajaxTransport.c.send @ kloudspeaker.full.min.js:8ia.extend.ajax @ kloudspeaker.full.min.js:8a.widget._onSend.j @ kloudspeaker.full.min.js:15a.widget._onSend @ kloudspeaker.full.min.js:15(anonymous function) @ kloudspeaker.full.min.js:9a.widget._addConvenienceMethods.c.submit @ kloudspeaker.full.min.js:15(anonymous function) @ kloudspeaker.full.min.js:15ia.Callbacks.l @ kloudspeaker.full.min.js:6ia.Callbacks.m.add @ kloudspeaker.full.min.js:6a.widget.options.add @ kloudspeaker.full.min.js:15a.Widget._trigger @ kloudspeaker.full.min.js:10(anonymous function) @ kloudspeaker.full.min.js:15ia.extend.each @ kloudspeaker.full.min.js:6a.widget._onAdd @ kloudspeaker.full.min.js:15(anonymous function) @ kloudspeaker.full.min.js:9(anonymous function) @ kloudspeaker.full.min.js:15ia.Callbacks.l @ kloudspeaker.full.min.js:6ia.Callbacks.m.add @ kloudspeaker.full.min.js:6ia.extend.Deferred.d.always @ kloudspeaker.full.min.js:6a.widget._onDrop @ kloudspeaker.full.min.js:15(anonymous function) @ kloudspeaker.full.min.js:9h @ kloudspeaker.full.min.js:10ia.event.dispatch @ kloudspeaker.full.min.js:7ia.event.add.r.handle @ kloudspeaker.full.min.js:7

**Comment by nnmalex** [comment]
I can confirm I have this issue as well. Doesn't happen all the time. Using Safari on Mac.

**Comment by chewi** [comment]
Me too on Opera 32.

**Comment by sjarvela** [comment]
So far I haven't been able to reproduce this, it would help if someone can come up with certain steps that reproduce it every time.

For example, does it happen with every kind of file? It really does not happen with regular upload?

If I had to guess, I'd say uploader is registered many times (or is not unregistered at some point) etc, which makes it handle upload events multiple times. This might happen when moving between folders, but still haven't seen this error.

**Comment by jasonPaddy** [comment]
Hi Sami,

if you drag and drop in RED rectangle area, there will be duplicates.
and it only uploads one copy if you just drag and drop in GREEN circle.

![screen shot 2015-09-28 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/12420731/10128099/04c5ad76-659d-11e5-9df3-cce8f3e07656.png)

**Comment by sjarvela** [comment]
ok, that may help...perhaps the drag event is bubbled up to the main file view (green) area as well, I'll check

**Comment by sjarvela** [comment]
I was able to reproduce this, and this commit seems to fix it: https://github.com/sjarvela/kloudspeaker/commit/81a0c70ab87b033fa56dda356cb7d6b1238670cb

**Comment by jasonPaddy** [comment]
Great work, mate.

**Comment by sjarvela** [comment]
In 2.7.7
