### ISSUE TITLE
search results not clickable

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#60]
Hi Mate,

version: 2.7.3

search function is not fully working. it could find right files.
but all files found can not be viewed/edited.

Symptom 01: 
left click on any search result threw below error in Chrome console
Uncaught Cannot resolve permission, permissions not fetchedhasFilesystemPermission @ kloudspeaker.full.min.js:20w._getCtxObj @ kloudspeaker.full.min.js:23w.itemWidget.init.onClick @ kloudspeaker.full.min.js:23onItemClick @ kloudspeaker.full.min.js:22(anonymous function) @ kloudspeaker.full.min.js:22(anonymous function) @ kloudspeaker.full.min.js:16
3kloudspeaker.full.min.js:20 Uncaught Cannot resolve permission, permissions not fetchedhasFilesystemPermission @ kloudspeaker.full.min.js:20(anonymous function) @ kloudspeaker.full.min.js:23l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6(anonymous function) @ kloudspeaker.full.min.js:6l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6d @ kloudspeaker.full.min.js:8d @ kloudspeaker.full.min.js:8

Sympton 02:
right click on any search result threw below error
Uncaught Cannot resolve permission, permissions not fetchedhasFilesystemPermission @ kloudspeaker.full.min.js:20(anonymous function) @ kloudspeaker.full.min.js:23l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6(anonymous function) @ kloudspeaker.full.min.js:6l @ kloudspeaker.full.min.js:6m.fireWith @ kloudspeaker.full.min.js:6d @ kloudspeaker.full.min.js:8d @ kloudspeaker.full.min.js:8

**Comment by RPuglia** [comment]
For me, with ver. 2.7.3, it works. I can right/left click on any file in search result with no error.

**Comment by nnmalex** [comment]
Works for me as well. Have you tried clearing cache and cookies?

**Comment by jasonPaddy** [comment]
Thanks Guys.
What permission does your test account has?
I am wondering if it's my account's permission issues.

**Comment by jasonPaddy** [comment]
just an update,
i subscribed same folder to admin user, and search function works as expected.
seems to be a permission issue on normal users.

**Comment by jasonPaddy** [comment]
Hi Sami,

this issue is reproducible.
1. login as admin, create a folder via web-gui.
2. create a normal user with RW and Delete permission
3. subscribe the folder to the normal user
4. login as the user normal, search any file, above errors showed up in console

**Comment by sjarvela** [comment]
Yes, I can see the reason. I have not yet implemented lazy permission fetching, ie only when needed, so now it relies on fact that all relevant permissions are fetched when listing is fetched.

Using admin user too often does not reveal all the aspects there should be considered, I'll fix this into next release.

**Comment by sjarvela** [comment]
This was actually due to custom folder type permission handling missing, permissions module did not know what to do with permissions request for search view itself (needs to know if this folder listing is writable).

Initial fix is in https://github.com/sjarvela/kloudspeaker/commit/ae3eb605571d437ae3f521763679611b5d9f9d78

**Comment by sjarvela** [comment]
Released in 2.7.4
