### ISSUE TITLE
2.7.5 permission editing issues

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#63]
I have noticed multiple issues of permission edit.
## File selection style/format is broken.

![screen shot 2015-09-28 at 2 22 21 pm](https://cloud.githubusercontent.com/assets/12420731/10127882/fbeca456-6598-11e5-8543-582cbf9607de.png)
## Once you click 'User permission' tab, it will stuck there. you can not go back to 'Item permissions' tab.

![screen shot 2015-09-28 at 2 22 54 pm](https://cloud.githubusercontent.com/assets/12420731/10127896/498f14f0-6599-11e5-96a8-3c2a763445b0.png)

**Comment by sjarvela** [comment]
Both fixed.

First was due to taking scss into use and splitting styles into separate files, but forgot to include one of them into main.scss.

Second was due to mistake in resolving clicked tab index.

**Comment by sjarvela** [comment]
in 2.7.6
