### ISSUE TITLE
2.7.5 blank home page due to core js file missing

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#64]
error GET http://192.168.97.10/kloudspeaker2.7.5/js/kloudspeaker.full.min.js

**Comment by jasonPaddy** [comment]
a short fix
copy kloudspeaker.full.min.js from older version

**Comment by chewi** [comment]
That file isn't supposed to be there any more. The correct fix is to change index.html to point to kloudspeaker.min.js instead.

**Comment by sjarvela** [comment]
Oh yes, forgot to mention the change in file naming. Updated also the example index.html: https://github.com/sjarvela/kloudspeaker/blob/master/backend/example/example_index.html
