### ISSUE TITLE
video viewer div and player overlap

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#65]
Hi Sami,

It would be great if you could increase the size of outer container so it does not overlap the inner player's timeline and control buttons.

bonus: auto resizing to to fit player's size would be even better, so we could remove both scroll bars.

![screen shot 2015-09-28 at 3 02 35 pm](https://cloud.githubusercontent.com/assets/12420731/10128203/f1321324-659e-11e5-8067-2b5092c00a97.png)

**Comment by sjarvela** [comment]
I made one small fix that improves the sizing a bit: https://github.com/sjarvela/kloudspeaker/commit/60ddb9df07d05bec1327b50efda9af2c84273303

There was unnecessary fixed size defined, without it the player will size itself according to the page around.

In wide-screen videos it also has some space at the bottom for the title bar.

In todo-list I have a task to rewrite the entire viewer plugin, so it would act better in different sizes and different viewer types, and something like next/prev buttons for switching between files in the folder.

**Comment by sjarvela** [comment]
The hover caption causes problems on many other cases as well, so for now I've made it visible always on bottom: https://github.com/sjarvela/kloudspeaker/commit/0d14e1e7e0b9d46ce6730a075d73247d259029ff

**Comment by sjarvela** [comment]
in 2.7.6
