### ISSUE TITLE
folder disappears if contains '/' in folder name

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#66]
![screen shot 2015-09-29 at 5 06 11 pm](https://cloud.githubusercontent.com/assets/12420731/10157331/7ccf44d2-66cc-11e5-9aa1-f4d9839bfa53.png)
![screen shot 2015-09-29 at 5 06 19 pm](https://cloud.githubusercontent.com/assets/12420731/10157332/7dc8390c-66cc-11e5-850e-446e9d90e0d8.png)

**Comment by sjarvela** [comment]
Slashes are no longer accepted in folder names

**Comment by sjarvela** [comment]
In 2.7.7
