### ISSUE TITLE
Is it possible to add a new page?

### ISSUE THREAD

**Issue by jasonPaddy** [sjarvela/kloudspeaker#68]
Hi Sam,

Is it possible to add new informative page right next to "Files" - "Configuration"?
such as 'Help' Page?

Cheers,
Jason

**Comment by jasonPaddy** [comment]
yo Sam,
any update would be appreciated.

**Comment by sjarvela** [comment]
Patience please, I'll do my best to react to all emails, issues, forum posts etc, but I only have limited time.

If you want a custom page added there, right now there is no easy way. I'll find a easy way to create custom main view pages.

**Comment by sjarvela** [comment]
I've now added possibility to register main views: https://github.com/sjarvela/kloudspeaker/commit/aabd8bdb8a8b276a1000bcbc504ab1461ca5a442

In next release, you can register your own main view after loading a custom module:

1) in kloudspeaker init

```
        "modules": {
            load: ['kloudspeaker/ui/dropbox', 'my-package'],
            paths: {
                'my-package': '/path/to/my-package'
            }
        },
```

2) create folder "my-package" into path defined

3) create main module "main.js" into folder "my-package"

```
        define(['kloudspeaker/ui/views'], function(views) {
            views.registerMainView({
                id: 'help',
                title: 'i18n:helpViewTitle',
                icon: 'question',
                view: 'my-package/main-help-page.html'
            });
        });
```

4) create "main-help-page.html" into folder "my-package"

Now when app is started, this will show new page icon in top bar, it will have font awesome icon "question" and title with localization key "helpViewTitle" (remove "i18n" to use non-localized title). When this view is opened, it will load "main-help-page.html" from your package folder.

I'll extend this in future so that there can be custom nav bar items etc, but this for a start.

**Comment by sjarvela** [comment]
In 2.7.7. Wiki documentation will be created later.

**Comment by jasonPaddy** [comment]
Hi Sam,

Thanks for the fix/improvement.
I installed 2.7.8 and made a view as per instruction.
It works pretty well.

There is one minor problem that I observed.
1. open the new view
2. resize browser window threw below errors, it does not seem to affect 
the page layout or anything else though.
Uncaught TypeError: b._currentView.onResize is not a function
b.onResize @ kloudspeaker.min.js:23
ia.event.dispatch @ kloudspeaker.min.js:7
ia.event.add.r.handle @ kloudspeaker.min.js:7

However, this issue does not apply on 'Files' or 'Configuration' view.

Cheers,
Jason

On 3/10/2015 9:09 pm, sjarvela wrote:

> I've now added possibility to register main views: aabd8bd 
> https://github.com/sjarvela/kloudspeaker/commit/aabd8bdb8a8b276a1000bcbc504ab1461ca5a442
> 
> In next release, you can register your own main view after loading a 
> custom module:
> 
> 1) in kloudspeaker init
> 
> |"modules": { load: ['kloudspeaker/ui/dropbox', 'my-package'], paths: { 
> 'my-package': '/path/to/my-package' } }, |
> 
> 2) create folder "my-package" into path defined
> 
> 3) create main module "main.js" into folder "my-package"
> 
> |define(['kloudspeaker/ui/views'], function(views) { 
> views.registerMainView({ id: 'help', title: 'i18n:helpViewTitle', 
> icon: 'question', view: 'my-package/main-help-page.html' }); }); |
> 
> 4) create "main-help-page.html" into folder "my-package"
> 
> Now when app is started, this will show new page icon in top bar, it 
> will have font awesome icon "question" and title with localization key 
> "helpViewTitle" (remove "i18n" to use non-localized title). When this 
> view is opened, it will load "main-help-page.html" from your package 
> folder.
> 
> I'll extend this in future so that there can be custom nav bar items 
> etc, but this for a start.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sjarvela/kloudspeaker/issues/68#issuecomment-145237038.

## 

Cheers,
Jason

**Comment by sjarvela** [comment]
Thanks for the info, I'll suppress that error
