### ISSUE TITLE
Add new folder fails in v2.7.8 with error 403

### ISSUE THREAD

**Issue by bfg9000d** [sjarvela/kloudspeaker#73]
When trying to add a new folder in v2.7.8, I get "Request failed" in a dialog and an error 403 in the console. 
This happens even using the most basic configuration file, and doesn't happen in version 2.7.6.
OBS: Using PHP 5.6.13.

**Comment by GeertM** [comment]
Having the same problem with my newly installed v2.7.8. Everything works except making a new folder.

Request failed

MySQLi DB: gecon_ks@localhost:gecon_ks()
DB QUERY: select id, user_id, ip, time, last_access from session where id = '1561d7e84f0811' and last_access >= 20151013215843
DB QUERY: select name, value from session_data where session_id = '1561d7e84f0811'
DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM user left outer join user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20151013235843)
DB QUERY: select id, name, description from user where id in (SELECT user_group.group_id FROM user as user, user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASC
DB QUERY: UPDATE session set last_access=20151013235843 where id='1561d7e84f0811'
Filesystem registered: local
EVENT HANDLER: registering 'filesystem/': FilesystemController
VERSION: 2.7.8 SERVER: {UNIQUE_ID:Vh1@ky4VrZMAAFCaO8UAAAAK, CONTENT_TYPE:application/json, HTTP_KLOUDSPEAKER_SESSION_ID:1561d7e84f0811, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_REFERER:http://portaal.geconbvba.be/?v=config/folders, CONTENT_LENGTH:31, HTTP_CACHE_CONTROL:no-cache, HTTP_COOKIE:mollify_app_session=156170140bef0c; kloudspeaker_app_session=1561d7e84f0811; mollify_app_session=156159dcda44a4, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:/home/gecon/domains/geconbvba.be/public_html/portaal, SCRIPT_FILENAME:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:, REQUEST_URI:/backend/r.php/configuration/folders, SCRIPT_NAME:/backend/r.php, PATH_INFO:/configuration/folders, PATH_TRANSLATED:/home/gecon/domains/geconbvba.be/public_html/portaal/configuration/folders, PHP_SELF:/backend/r.php/configuration/folders, REQUEST_TIME_FLOAT:1444773523.92, REQUEST_TIME:1444773523}
SETTINGS: {db:{type:mysql, database:gecon_ks, user:gecon_ks, password:, charset:utf8}, plugins:{FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}}, ItemDetails:{}}, host_public_address:http://portaal.geconbvba.be, timezone:Europe/Brussels, enable_limited_http_methods:, debug:1, debug_log:/home/gecon/domains/geconbvba.be/public_html/portaal/debug.log, published_folders_root:/portaal/custom}
FEATURES: {limited_http_methods:, change_password:1, descriptions:1, user_groups:1, mail_notification:, retrieve_url:, folder_protection:, thumbnails:, guest_mode:, file_view:1, file_preview:1, file_edit:1}
FILESYSTEM: allowed_file_upload_types={}
SESSION: is_active=1, user={id:1, name:MyUseriID, user_type:a, lang:, email:, expiration:, auth:}, data={auth:}
AUTH: is_authenticated=1
REQUEST: method=post, path={0:configuration, 1:folders}, ip=84.196.34.82, params={mollify_app_session:156170140bef0c, kloudspeaker_app_session:1561d7e84f0811}, data={name:Geert, path:geert}
SERVICE (ConfigurationServices)
ServiceException: INVALID_REQUEST=Invalid ConfigurationServices request: POST configuration/folders Invalid name
{0:{file:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/include/services/ConfigurationServices.class.php, line:656, function:invalidRequestException, class:ServicesBase, type:->, args:{0:Invalid name}}, 1:{file:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/include/services/ConfigurationServices.class.php, line:62, function:processPostFolders, class:ConfigurationServices, type:->, args:{}}, 2:{file:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/include/services/ServicesBase.class.php, line:69, function:processPost, class:ConfigurationServices, type:->, args:{}}, 3:{file:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/include/KloudspeakerBackend.class.php, line:85, function:processRequest, class:ServicesBase, type:->, args:{}}, 4:{file:/home/gecon/domains/geconbvba.be/public_html/portaal/backend/r.php, line:81, function:processRequest, class:KloudspeakerBackend, type:->, args:{0:Request}}}
RESPONSE error {0:101, 1:Invalid request, 2:403} Invalid ConfigurationServices request: POST configuration/folders Invalid name 

Any idea?

**Comment by rongten** [comment]
I do not know php, but maybe  the "\"  check at line 656 of ConfigurationServices.class.php should be a simple (strpos($name, "\\")) instead of (strpos($name, "\\") >=0 ) - or what was there before. Doing this allows me to create a folder.

**Comment by sjarvela** [comment]
Yes, there is a mistake. In java world you expect index to be -1 if not found, in PHP it returns FALSE if not found.

So correct form would be "strpos(...) !== FALSE", I'll fix it asap.

**Comment by GeertM** [comment]
Thanks, i made the change and it worked! Thanks!
I can now make root folders without any problem. Unfortunately i can't files to them (Request failed). No error appears in the debug.log. In the 'item_id' sql table only root dirs appear.
Still something missing?

**Comment by GeertM** [comment]
All fixed in v2.7.9. Thanks!
