### ISSUE TITLE
Filename truncation

### ISSUE THREAD

**Issue by crashmaxed** [sjarvela/kloudspeaker#76]
I'm not sure exactly what naming convention triggers it, but I was doing some testing and I noticed that filenames are being truncated at times.  This is happening in the latest release, 2.7.9. 

In the first example Chrome is truncating the filename while both IE and Firefox displayed the name properly.

![chrome_issue](https://cloud.githubusercontent.com/assets/9369535/10619408/c4c59202-7732-11e5-9bdd-4cd388ef5c61.png)

Later on I found another filename that triggers it, but this time it does it in all browsers.  Note though that Firefox is truncating more than IE or Chrome.

![all_issue](https://cloud.githubusercontent.com/assets/9369535/10619776/ce0f66f6-7734-11e5-8ea8-0b68a4589deb.png)

**Comment by sjarvela** [comment]
In case of long filenames, there's default browser word break used, which breaks the line after words, in your case after "-", leaving only short fraction visible.

I've now changed word break into "word-break: break-all", committed https://github.com/sjarvela/kloudspeaker/commit/74c40c1dc6bb8e074c3ccda3adaf620c0fed6a52
