### ISSUE TITLE
Notification for a new user

### ISSUE THREAD

**Issue by GeertM** [sjarvela/kloudspeaker#77]
Hi all, any idea if it is possible to make a notification to the email address of a newly created user to inform this person that a login is created, showing his username, password and the url of the login page?

**Comment by sjarvela** [comment]
Unfortunately no, this is not yet possible. Notificator system allows only setting up static recipients, ie. "if A happens, send mail to B", so there is no possibility to say "if A happens, send mail to <something from the event>" (in this case, "something from the event" would be user created).

This has been requested once before: https://github.com/sjarvela/kloudspeaker/issues/40

**Comment by sjarvela** [comment]
Closing as duplicate, will continue on the earlier issue
