### ISSUE TITLE
failed to create new folder

### ISSUE THREAD

**Issue by kosmynin** [sjarvela/kloudspeaker#78]
Hi,
I'm using v2.7.9 and get the following error everytime i want to create a new folder. 

```
MySQLi DB: kloudspeaker@localhost:kloudspeaker()
EVENT HANDLER: registering 'filesystem/': CommentHandler
EVENT HANDLER: registering 'filesystem/': ShareHandler
EVENT HANDLER: registering 'filesystem/': ItemCollectionHandler
EVENT HANDLER: registering 'user/': ItemCollectionHandler
DB QUERY: select id, user_id, ip, time, last_access from session where id = '1562ce01f61ac3' and last_access >= 20151025145659
DB QUERY: select name, value from session_data where session_id = '1562ce01f61ac3'
DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM user left outer join user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20151025165659)
DB QUERY: select id, name, description from user where id in (SELECT user_group.group_id FROM user as user, user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASC
DB QUERY: UPDATE session set last_access=20151025165659 where id='1562ce01f61ac3'
Filesystem registered: local
EVENT HANDLER: registering 'filesystem/': FilesystemController
VERSION: 2.7.9 SERVER: {CONTENT_TYPE:application/json; charset=UTF-8, HTTP_KLOUDSPEAKER_SESSION_ID:1562ce01f61ac3, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_REFERER:http://kosmynin.myftp.org/?v=files/562c02f9eae15, CONTENT_LENGTH:15, HTTP_COOKIE:uppodhtml5_volume=0.8; PHPSESSID=r3lo5dlspfbu6681fn76afl462; AjaXplorer=3r9tdc5j5amon7m8jtsahpev84; AjaXplorer-remember=admin%3A0329294b8ae8a0c88411df9d7890e8be; __CJ_ajxp_remember=%7B%22user%22%3A%22notify%22%2C%22pass%22%3A%22notify%22%7D; freehold_session=admin_HBdKVGijClEQSlBnbBWQE2wdvXyCEqtJhlJlNxmgCRQ=; kloudspeaker_app_login=1%3A48bc1b5367c552c54eb6a295edfa76b2; kloudspeaker_app_session=1562ce01f61ac3, HTTP_PRAGMA:no-cache, HTTP_CACHE_CONTROL:no-cache, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:/var/www/html, SCRIPT_FILENAME:/var/www/html/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:, REQUEST_URI:/backend/r.php/filesystem/562c02f9eae15/folders/, SCRIPT_NAME:/backend/r.php, PATH_INFO:/filesystem/562c02f9eae15/folders/, PATH_TRANSLATED:/var/www/html/filesystem/562c02f9eae15/folders/, PHP_SELF:/backend/r.php/filesystem/562c02f9eae15/folders/, REQUEST_TIME_FLOAT:1445785019.228, REQUEST_TIME:1445785019}
SETTINGS: {db:{type:mysql, user:kloudspeaker, password:}, plugins:{Archiver:{compressor:native, enable_download:1, enable_compress:1, enable_extract:1}, FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}, TextFile:{0:txt, 1:js, 2:css, 3:xml, 4:html, 5:xhtml, 6:py, 7:c, 8:cpp, 9:as3, 10:sh, 11:java, 12:sql, 13:php}, JPlayer:{0:mp3, 1:ogg}, FlowPlayer:{0:mp4, 1:flv}, ViewerJS:{0:pdf, 1:odt, 2:ods, 3:odp}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}, editors:{TextFile:{0:txt, 1:tex, 2:js, 3:css, 4:xml, 5:html, 6:xhtml, 7:py, 8:c, 9:cpp, 10:as3, 11:sh, 12:java, 13:php}}}, Comment:{}, Share:{}, ItemDetails:{}, ItemCollection:{}}, debug:1, debug_log:/var/www/html/backend/debug.log}
FEATURES: {limited_http_methods:, change_password:1, descriptions:1, user_groups:1, mail_notification:, retrieve_url:, folder_protection:, thumbnails:, guest_mode:, file_view:1, file_preview:1, file_edit:1, itemcollection:1}
FILESYSTEM: allowed_file_upload_types={}
SESSION: is_active=1, user={id:1, name:admin, user_type:a, lang:, email:, expiration:, auth:}, data={auth:cookie}
AUTH: is_authenticated=1
REQUEST: method=post, path={0:filesystem, 1:562c02f9eae15, 2:folders}, ip=fe80::b856:cb5b:c833:8bd2, params={}, data={name:test}
SERVICE (FilesystemServices)
DB QUERY: select path from item_id where id='562c02f9eae15'
DB QUERY: SELECT id, type, name, path FROM folder where id='1'
DB QUERY: select id from item_id where path='1:/'
creating folder [562c02f9eae15/test]
DB QUERY: select id from item_id where path='1:/test/'
DB QUERY: INSERT INTO item_id (id, path) VALUES ('562cedbfa84fc','1:/test/')
PHP error #2, chmod(): Operation not permitted (/var/www/html/backend/include/filesystem/LocalFilesystem.class.php:421) {0:{function:globalErrorHandler, args:{0:2, 1:chmod(): Operation not permitted, 2:/var/www/html/backend/include/filesystem/LocalFilesystem.class.php, 3:421, 4:{folder:FILESYSTEMITEM Folder (LocalFilesystem): [562c02f9eae15] = 'HDD' (), name:test, path:/media/hdd/test/, nativePath:/media/hdd/test/}}}, 1:{file:/var/www/html/backend/include/filesystem/LocalFilesystem.class.php, line:421, function:chmod, args:{0:/media/hdd/test/, 1:493}}, 2:{file:/var/www/html/backend/include/filesystem/FilesystemItem.class.php, line:193, function:createFolder, class:LocalFilesystem, object:LOCAL (1) HDD(/media/hdd/), type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [562c02f9eae15] = 'HDD' (), 1:test}}, 3:{file:/var/www/html/backend/include/filesystem/FilesystemController.class.php, line:1105, function:createFolder, class:Folder, object:FILESYSTEMITEM Folder (LocalFilesystem): [562c02f9eae15] = 'HDD' (), type:->, args:{0:test}}, 4:{file:/var/www/html/backend/include/services/FilesystemServices.class.php, line:453, function:createFolder, class:FilesystemController, object:FILESYSTEMCONTROLLER, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [562c02f9eae15] = 'HDD' (), 1:test}}, 5:{file:/var/www/html/backend/include/services/FilesystemServices.class.php, line:67, function:processPostFolder, class:FilesystemServices, object:FileSystemServices, type:->, args:{0:FILESYSTEMITEM Folder (LocalFilesystem): [562c02f9eae15] = 'HDD' ()}}, 6:{file:/var/www/html/backend/include/services/ServicesBase.class.php, line:69, function:processPost, class:FilesystemServices, object:FileSystemServices, type:->, args:{}}, 7:{file:/var/www/html/backend/include/KloudspeakerBackend.class.php, line:85, function:processRequest, class:ServicesBase, object:FileSystemServices, type:->, args:{}}, 8:{file:/var/www/html/backend/r.php, line:81, function:processRequest, class:KloudspeakerBackend, object:KloudspeakerBackend, type:->, args:{0:Request}}}
RESPONSE error {0:999, 1:Unexpected server error, 2:500} PHP error #2, chmod(): Operation not permitted (/var/www/html/backend/include/filesystem/LocalFilesystem.class.php:421) 
```

The message says "Request failed" but after pressing "OK" the folder is shown and browsable by kloudspeaker and the normal file explorer.

**Comment by sjarvela** [comment]
You seem to have setting "new_folder_permission_mask" defined, and so server tries to assign this permission mask for created root folders in OS filesystem.

But it seems this is forbidden for PHP, so you need to remove this setting, and see if you really even need this.

**Comment by kosmynin** [comment]
I haven't defined "new_folder_permission_mask" in the backend configuration.php

**Comment by sjarvela** [comment]
Oh yes, there is default value for this.

Default value 0755 means "rwx" for owner, "rx" for group and other. For some reason you don't have permission for using chmod, like the folder is not really owned by the PHP user? You should check from the server, which user/group owns these created folders, and then figure out why this does not work, ie if you need to use different mask, or is there some case where this cannot be used at all.

I'll make a change, where this value can be disabled, for example with value FALSE it won't even try.

**Comment by kosmynin** [comment]
Thank You
The problem was caused by the usage of an external HDD which was mounted with fstab but by the wrong user (owner folder != owner server). Correcting that solved the error.

**Comment by sjarvela** [comment]
Glad to hear

**Comment by carlosamaya** [comment]
Hi fellows, i have the same problem, but the Folder are in the same web-server, the user that owns the folder is www-data i think its the same user that PHP uses, also i changed the folder access to 777 and even so doesnt grant me acces to mkdir...please help:

MySQLi DB: mollify@localhost:mollify(mollify_)
EVENT HANDLER: registering '*': EventLogger
DB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '15727379954bed' and last_access >= 20160502045854
DB QUERY: select name, value from mollify_session_data where session_id = '15727379954bed'
DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='79' AND (expiration is null or expiration > 20160502065854)
DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '79') ORDER BY id ASC
DB QUERY: UPDATE mollify_session set last_access=20160502065854 where id='15727379954bed'
Filesystem registered: local
EVENT HANDLER: registering 'filesystem/': FilesystemController
VERSION: 2.6.7 SERVER: {PHPRC:/opt/php/bin/php-5.3.3/bin/etc/php.ini, PWD:/var/www/cgi-bin, FCGI_ROLE:RESPONDER, REDIRECT_HANDLER:php-cgi, REDIRECT_STATUS:200, CONTENT_LENGTH:62, HTTP_ORIGIN:http://172.28.24.83, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_MOLLIFY_SESSION_ID:15727379954bed, CONTENT_TYPE:application/json, HTTP_REFERER:http://172.28.24.83/visdoc/?v=admin/folders, HTTP_COOKIE:PHPSESSID=iegh96m8rqvs286k4mvu9uggr0; mollify_app_session=15727379954bed, HTTP_X_BLUECOAT_VIA:f353c8eb22c0e2cd, REQUEST_SCHEME:http, CONTEXT_PREFIX:/php5-cgi/, CONTEXT_DOCUMENT_ROOT:/var/www/cgi-bin/, SCRIPT_FILENAME:/var/www/php-5.3.3/visdoc/backend/r.php, REDIRECT_URL:/visdoc/backend/r.php/configuration/folders, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:, REQUEST_URI:/visdoc/backend/r.php/configuration/folders, SCRIPT_NAME:/visdoc/backend/r.php, PATH_INFO:/configuration/folders, PATH_TRANSLATED:/var/www/configuration/folders, ORIG_PATH_INFO:/visdoc/backend/r.php/configuration/folders, ORIG_SCRIPT_NAME:/php5-cgi/php-5.3.3.fcgi, ORIG_SCRIPT_FILENAME:/var/www/cgi-bin/php-5.3.3.fcgi, ORIG_PATH_TRANSLATED:/var/www/php-5.3.3/visdoc/backend/r.php/configuration/folders, PHP_SELF:/visdoc/backend/r.php/configuration/folders, REQUEST_TIME:1462188534}
SETTINGS: {db:{type:mysql, user:mollify, password:, host:localhost, port:3306, database:mollify, table_prefix:mollify_, charset:utf8_general_ci, engine:MyISAM}, plugins:{FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}}, previewers:{Image:{0:gif, 1:png, 2:jpg, 3:jpeg}}}, ItemDetails:{}, EventLogging:{}}, timezone:America/Caracas, convert_filenames:1, authentication_methods:{0:pw, 1:ldap}, ldap_server:ldap://pdvsa.com, debug:1, debug_log:/var/www/php-5.3.3/visdoc/logs/visdoc_pdvsa.log}
FEATURES: {limited_http_methods:, change_password:1, descriptions:1, user_groups:1, mail_notification:, retrieve_url:, folder_protection:, thumbnails:, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}
FILESYSTEM: allowed_file_upload_types={}
SESSION: is_active=1, user={id:79, name:amayacl, user_type:a, lang:, email:amayacl@XXXXXXX.com, expiration:20180131142544, auth:}, data={auth:}
AUTH: is_authenticated=1
REQUEST: method=post, path={0:configuration, 1:folders}, ip=162.122.76.241, params={}, data={name:HomeFolder, path:/MiDoc/HomeFolder, create:1}
SERVICE (ConfigurationServices)
Added folder does not exist, creating: /MiDoc/HomeFolder
PHP error #2, mkdir(): Permission denied (/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php:43) {0:{function:globalErrorHandler, args:{0:2, 1:mkdir(): Permission denied, 2:/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php, 3:43, 4:{rootPath:/MiDoc/HomeFolder/}}}, 1:{file:/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php, line:43, function:mkdir, args:{0:/MiDoc/HomeFolder/, 1:493}}, 2:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ConfigurationServices.class.php, line:662, function:create, class:LocalFilesystem, object:LOCAL () HomeFolder(/MiDoc/HomeFolder/), type:->, args:{}}, 3:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ConfigurationServices.class.php, line:62, function:processPostFolders, class:ConfigurationServices, object:ConfigurationServices, type:->, args:{}}, 4:{file:/var/www/php-5.3.3/visdoc/backend/include/services/ServicesBase.class.php, line:59, function:processPost, class:ConfigurationServices, object:ConfigurationServices, type:->, args:{}}, 5:{file:/var/www/php-5.3.3/visdoc/backend/include/MollifyBackend.class.php, line:85, function:processRequest, class:ServicesBase, object:ConfigurationServices, type:->, args:{}}, 6:{file:/var/www/php-5.3.3/visdoc/backend/r.php, line:81, function:processRequest, class:MollifyBackend, object:MollifyBackend, type:->, args:{0:Request}}}
RESPONSE error {0:999, 1:Unexpected server error, 2:500} PHP error #2, mkdir(): Permission denied (/var/www/php-5.3.3/visdoc/backend/include/filesystem/LocalFilesystem.class.php:43)
