### ISSUE TITLE
After install, get no home page

### ISSUE THREAD

**Issue by tangmeng09** [sjarvela/kloudspeaker#79]
End at http://xxx/kloudspeaker/backend/install/#. 
Waste of time.

**Comment by sjarvela** [comment]
Perhaps some error log or something?

**Comment by eae710** [comment]
After install, I login as administrator and get this error console js: "Uncaught Cannot resolve permission, permissions not fetched" Any idea?

**Comment by eae710** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/472642/12103093/2bfc6974-b305-11e5-85d6-81a1be4e7e21.png)

**Comment by sjarvela** [comment]
This was fixed in 2.7.11. Problem was that client tried to resolve permissions for folders, when there were none.
