### ISSUE TITLE
item_description table not created with the mysql backend?

### ISSUE THREAD

**Issue by rongten** [sjarvela/kloudspeaker#80]
Hello,
I was having errors like:
KLOUDSPEAKER ERROR: ServiceException: INVALID_CONFIGURATION=Error executing query (DELETE FROM item_description WHERE item_id in ('5631edaee17fd','5631edaee17fd')): Table 'kloudspeaker.item_description' doesn't exist

In the postgresql install script there was mention of this table and in the mysql not. I created it manually like 
create table item_description ( `item_id` char(255) NOT NULL, `description` varchar(512) NOT NULL, PRIMARY KEY (`item_id`) ) ENGINE = '{ENGINE}' COLLATE utf8_general_ci COMMENT = 'Kloudspeaker item descriptions';

and now it seems it work and I can create permissions.

**Comment by sjarvela** [comment]
Table "item_description" has been deprecated, it is stored in metadata table instead. It seems few places still refer to it, I have removed them in commit https://github.com/sjarvela/kloudspeaker/commit/33c5fc947b581ef511636652af7dbd7894bed606

Support for postgresql was never finished, so the tables are old.

**Comment by rongten** [comment]
Ok. I assume I can then drop the table and apply the patch and all should be fine on an existing server then.

**Comment by sjarvela** [comment]
Yes, you can make changes according to commit https://github.com/sjarvela/kloudspeaker/commit/33c5fc947b581ef511636652af7dbd7894bed606 (or, of course, wait for next release).

After these changes, the table can be dropped.

**Comment by sjarvela** [comment]
Removed in 2.7.11
