### ISSUE TITLE
Error en WebDav Component

### ISSUE THREAD

**Issue by thejoepeach** [sjarvela/kloudspeaker#88]
Hi there, i am having this error using the WebDav Component, any ideas on what i don wrong?

``` php
Fatal error: Uncaught exception 'Sabre_DAV_Exception_BadRequest' in /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/kloudspeaker_dav.php:379 Stack trace: #0 /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/index.php(11): require_once() #1 {main} thrown in /mounted-storage/home39a/sub003/sc26785-PFHU/freefallmotion.com/files/backend/dav/kloudspeaker_dav.php on line 379
```

I cant find any reference about this error on the kloudspeaker site or SabreDav Site... so any help will be appreciated

**Comment by sjarvela** [comment]
As I replied in discussion group, I think you are using folder with name "Docs" and path "docs", and this is relative path. It works when you are using the web UI, but webdav is located in different location, and relative path now points to different location which does not exist.

So always use absolute paths, or alternatively use setting: https://github.com/sjarvela/kloudspeaker/wiki/Backend-configuration-options#published-folders-root-published_folders_root
