### ISSUE TITLE
No scrollbar in full layout

### ISSUE THREAD

**Issue by crashmaxed** [sjarvela/kloudspeaker#89]
I've noticed that after assigning a bunch of folders that there is no scrollbar if the number of folders is too long for the screen when the responsive theme is in the full layout:

![reg_no_scroll](https://cloud.githubusercontent.com/assets/9369535/11478407/11705786-974a-11e5-8f39-8f65f97a48b6.png)

Currently the only way to scroll is to shrink the browser width to a point where the responsive layout changes and removes the header items (puts them in a sort of menu button dropdown).  At that point the browser's regular scroll bar allows you to see the whole list:

![res_scroll2](https://cloud.githubusercontent.com/assets/9369535/11479688/889a3eb6-9750-11e5-836a-6d1df3f92332.png)

The very small width responsive layout also works:  

![res_scroll](https://cloud.githubusercontent.com/assets/9369535/11478438/36a68d54-974a-11e5-9636-aa75f1a442b9.png)

It looks like the issue isn't with the scroll bar being hidden, but rather the browser thinking that the body is smaller in the y resolution than it really is and as such not displaying any scroll bar.  Using the browser's inspector against the body element shows this:

![inspect_full](https://cloud.githubusercontent.com/assets/9369535/11480546/30c2a75a-9755-11e5-8370-0d6230cfde83.png)

![inspect_mid](https://cloud.githubusercontent.com/assets/9369535/11480625/a194e0b0-9755-11e5-9f3a-dc2d52743388.png)

![inspec_small](https://cloud.githubusercontent.com/assets/9369535/11480629/a371a9ea-9755-11e5-81a0-66f5160af345.png)

**Comment by sjarvela** [comment]
Fixed
