### ISSUE TITLE
How to interrupt a file upload

### ISSUE THREAD

**Issue by luke7263** [sjarvela/kloudspeaker#9]
Currently the only way to interrupt a file upload seems to refresh the whole page. It would be smart to have a close button  to cancel a slow upload, example below ..;)

![upload](https://cloud.githubusercontent.com/assets/11775011/7084198/e5642b96-df6a-11e4-94c5-d851f5cb725c.png)

**Comment by sjarvela** [comment]
Yes, it should be possible to abort upload, I'll investigate this.

**Comment by sjarvela** [comment]
In 2.6.9
