### ISSUE TITLE
Is this work in Azure Web Sites?

### ISSUE THREAD

**Issue by alexsandro-xpt** [sjarvela/kloudspeaker#90]
After login, my `console.log` give an exception `Uncaught Cannot resolve permission, permissions not fetched` from `kloudspeaker.min.js`.

What´s could happen? IIS permission?

**Comment by sjarvela** [comment]
What version do you have? Can you paste entire error from console? Any other steps required, besides just log in?

**Comment by alexsandro-xpt** [comment]
No more, I uninstalled kloudspeaker, thanks.

**Comment by sjarvela** [comment]
This was only visible in empty setup, ie no folders defined, fixed now.
