### ISSUE TITLE
Multiple search criteria

### ISSUE THREAD

**Issue by andrelecomte** [sjarvela/kloudspeaker#92]
It would be great if Kloudspeaker would allow for multiple search terms, eg. search for file names containing both the words 'red' and 'car'.

**Comment by b-and-p** [comment]
I recently wrote this hack that may help [Kloudspeaker regex search](https://groups.google.com/forum/#!topic/kloudspeaker/WEt2qs7v1I4)

**Comment by andrelecomte** [comment]
This is great! I will try it. Thank you!
