### ISSUE TITLE
Not working in Firefox 43.0.4

### ISSUE THREAD

**Issue by jbl105** [sjarvela/kloudspeaker#98]
So I am positive I am missing something but I am having an issue getting this working with any plugins. When I use the standard MySQL example configuration I can't get it to work in firefox if I comment out all plugin section then it will work in IE and Firefox. 
Kloudspeaker 2.7.10
Firefox 43.0.4
IE 10

<?php

/\* For configuration instructions, see ReadMe.txt or wiki page at https://github.com/sjarvela/kloudspeaker/wiki/Installation */

$CONFIGURATION = array(
    "db" => array(
        "type" => "mysql",
        "database" => "kloudspeaker",
        "host" => "EDITED OUT FOR SECURITY",
        "user" => "EDITED OUT FOR SECURITY",
        "password" => "EDITED OUT FOR SECURITY",
        "charset" => "utf8",
    ),
    "timezone" => "Europe/Helsinki", // change this to match your timezone

```
"plugins" => array(
    "FileViewerEditor" => array(
        "viewers" => array(
            "Image" => array("gif", "png", "jpg"),
        ),
        "previewers" => array(
            "Image" => array("gif", "png", "jpg"),
        ),
    ),
    "ItemDetails" => array(),
),
```

);

?>

This will load up and work in IE but not firefox. I get two errors via firebug and it won't load....

Error: Script error for: kloudspeaker/fileviewereditor/main
http://requirejs.org/docs/errors.html#scripterror 

Error: Script error for: kloudspeaker/itemdetails/main
http://requirejs.org/docs/errors.html#scripterror

Both reference 13996 kloudspeaker.js

If I comment out plugins then it will work in both can anyone please advice me on where I have messed up?

**Comment by sjarvela** [comment]
No obvious error in configuration that I could spot. The script error would indicate it is unable to load the client module script.

First check that there is "client/main.js" under "backend/plugin/FileViewerEditor" and ".../ItemDetails".

Would it be possible to see that site myself? if so, you can email details to kloudspeaker(at)gmail.com

**Comment by jbl105** [comment]
I checked that there is "client/main.js" under "backend/plugin/FileViewerEditor" and ".../ItemDetails". I also sent you site info so you could check it out if you get time. Thank you for all the help!

**Comment by sjarvela** [comment]
seems to be some godaddy issue
